package me.zaydbille.pokedex.utils;

import me.zaydbille.pokedex.R;

/**
 * Created by Zayd on 6/19/16.
 */
public final class SpriteUtils {

    public static int getSprite(int pokemonId, String rawName){ return R.drawable.p0; }
    public static int getShinySprite(int pokemonId, String rawName){ return R.drawable.p0; }
    /*
    public static int getSprite(int pokemonId, String rawName) {
        if (pokemonId == 1) { return R.drawable.p1; }
        if (pokemonId == 2) { return R.drawable.p2; }
        if (pokemonId == 3) { return R.drawable.p3; }
        if (pokemonId == 3) { return R.drawable.p3; }
        if (pokemonId == 4) { return R.drawable.p4; }
        if (pokemonId == 5) { return R.drawable.p5; }
        if (pokemonId == 6) { return R.drawable.p6; }
        if (pokemonId == 6) { return R.drawable.p6; }
        if (pokemonId == 6) { return R.drawable.p6; }
        if (pokemonId == 7) { return R.drawable.p7; }
        if (pokemonId == 8) { return R.drawable.p8; }
        if (pokemonId == 9) { return R.drawable.p9; }
        if (pokemonId == 9) { return R.drawable.p9; }
        if (pokemonId == 10) { return R.drawable.p10a; }
        if (pokemonId == 11) { return R.drawable.p11a; }
        if (pokemonId == 12) { return R.drawable.p12a; }
        if (pokemonId == 13) { return R.drawable.p13a; }
        if (pokemonId == 14) { return R.drawable.p14a; }
        if (pokemonId == 15) { return R.drawable.p15a; }
        if (pokemonId == 15) { return R.drawable.p15a; }
        if (pokemonId == 16) { return R.drawable.p16a; }
        if (pokemonId == 17) { return R.drawable.p17a; }
        if (pokemonId == 18) { return R.drawable.p18a; }
        if (pokemonId == 18) { return R.drawable.p18a; }
        if (pokemonId == 19) { return R.drawable.p19a; }
        if (pokemonId == 20) { return R.drawable.p20a; }
        if (pokemonId == 21) { return R.drawable.p21a; }
        if (pokemonId == 22) { return R.drawable.p22a; }
        if (pokemonId == 23) { return R.drawable.p23a; }
        if (pokemonId == 24) { return R.drawable.p24a; }
        if (pokemonId == 25) { return R.drawable.p25a; }
        if (pokemonId == 25) { return R.drawable.p25a; }
        if (pokemonId == 25) { return R.drawable.p25a; }
        if (pokemonId == 25) { return R.drawable.p25a; }
        if (pokemonId == 25) { return R.drawable.p25a; }
        if (pokemonId == 25) { return R.drawable.p25a; }
        if (pokemonId == 25) { return R.drawable.p25a; }
        if (pokemonId == 26) { return R.drawable.p26a; }
        if (pokemonId == 27) { return R.drawable.p27a; }
        if (pokemonId == 28) { return R.drawable.p28a; }
        if (pokemonId == 29) { return R.drawable.p29a; }
        if (pokemonId == 30) { return R.drawable.p30a; }
        if (pokemonId == 31) { return R.drawable.p31a; }
        if (pokemonId == 32) { return R.drawable.p32a; }
        if (pokemonId == 33) { return R.drawable.p33a; }
        if (pokemonId == 34) { return R.drawable.p34a; }
        if (pokemonId == 35) { return R.drawable.p35a; }
        if (pokemonId == 36) { return R.drawable.p36a; }
        if (pokemonId == 37) { return R.drawable.p37a; }
        if (pokemonId == 38) { return R.drawable.p38a; }
        if (pokemonId == 39) { return R.drawable.p39a; }
        if (pokemonId == 40) { return R.drawable.p40a; }
        if (pokemonId == 41) { return R.drawable.p41a; }
        if (pokemonId == 42) { return R.drawable.p42a; }
        if (pokemonId == 43) { return R.drawable.p43a; }
        if (pokemonId == 44) { return R.drawable.p44a; }
        if (pokemonId == 45) { return R.drawable.p45a; }
        if (pokemonId == 46) { return R.drawable.p46a; }
        if (pokemonId == 47) { return R.drawable.p47a; }
        if (pokemonId == 48) { return R.drawable.p48a; }
        if (pokemonId == 49) { return R.drawable.p49a; }
        if (pokemonId == 50) { return R.drawable.p50a; }
        if (pokemonId == 51) { return R.drawable.p51a; }
        if (pokemonId == 52) { return R.drawable.p52a; }
        if (pokemonId == 53) { return R.drawable.p53a; }
        if (pokemonId == 54) { return R.drawable.p54a; }
        if (pokemonId == 55) { return R.drawable.p55a; }
        if (pokemonId == 56) { return R.drawable.p56a; }
        if (pokemonId == 57) { return R.drawable.p57a; }
        if (pokemonId == 58) { return R.drawable.p58a; }
        if (pokemonId == 59) { return R.drawable.p59a; }
        if (pokemonId == 60) { return R.drawable.p60a; }
        if (pokemonId == 61) { return R.drawable.p61a; }
        if (pokemonId == 62) { return R.drawable.p62a; }
        if (pokemonId == 63) { return R.drawable.p63a; }
        if (pokemonId == 64) { return R.drawable.p64a; }
        if (pokemonId == 65) { return R.drawable.p65a; }
        if (pokemonId == 65) { return R.drawable.p65a; }
        if (pokemonId == 66) { return R.drawable.p66a; }
        if (pokemonId == 67) { return R.drawable.p67a; }
        if (pokemonId == 68) { return R.drawable.p68a; }
        if (pokemonId == 69) { return R.drawable.p69a; }
        if (pokemonId == 70) { return R.drawable.p70a; }
        if (pokemonId == 71) { return R.drawable.p71a; }
        if (pokemonId == 72) { return R.drawable.p72a; }
        if (pokemonId == 73) { return R.drawable.p73a; }
        if (pokemonId == 74) { return R.drawable.p74a; }
        if (pokemonId == 75) { return R.drawable.p75a; }
        if (pokemonId == 76) { return R.drawable.p76a; }
        if (pokemonId == 77) { return R.drawable.p77a; }
        if (pokemonId == 78) { return R.drawable.p78a; }
        if (pokemonId == 79) { return R.drawable.p79a; }
        if (pokemonId == 80) { return R.drawable.p80a; }
        if (pokemonId == 80) { return R.drawable.p80a; }
        if (pokemonId == 81) { return R.drawable.p81a; }
        if (pokemonId == 82) { return R.drawable.p82a; }
        if (pokemonId == 83) { return R.drawable.p83a; }
        if (pokemonId == 84) { return R.drawable.p84a; }
        if (pokemonId == 85) { return R.drawable.p85a; }
        if (pokemonId == 86) { return R.drawable.p86a; }
        if (pokemonId == 87) { return R.drawable.p87a; }
        if (pokemonId == 88) { return R.drawable.p88a; }
        if (pokemonId == 89) { return R.drawable.p89a; }
        if (pokemonId == 90) { return R.drawable.p90a; }
        if (pokemonId == 91) { return R.drawable.p91a; }
        if (pokemonId == 92) { return R.drawable.p92a; }
        if (pokemonId == 93) { return R.drawable.p93a; }
        if (pokemonId == 94) { return R.drawable.p94a; }
        if (pokemonId == 94) { return R.drawable.p94a; }
        if (pokemonId == 95) { return R.drawable.p95a; }
        if (pokemonId == 96) { return R.drawable.p96a; }
        if (pokemonId == 97) { return R.drawable.p97a; }
        if (pokemonId == 98) { return R.drawable.p98a; }
        if (pokemonId == 99) { return R.drawable.p99a; }
        if (pokemonId == 100) { return R.drawable.p100a; }
        if (pokemonId == 101) { return R.drawable.p101a; }
        if (pokemonId == 102) { return R.drawable.p102a; }
        if (pokemonId == 103) { return R.drawable.p103a; }
        if (pokemonId == 104) { return R.drawable.p104a; }
        if (pokemonId == 105) { return R.drawable.p105a; }
        if (pokemonId == 106) { return R.drawable.p106a; }
        if (pokemonId == 107) { return R.drawable.p107a; }
        if (pokemonId == 108) { return R.drawable.p108a; }
        if (pokemonId == 109) { return R.drawable.p109a; }
        if (pokemonId == 110) { return R.drawable.p110a; }
        if (pokemonId == 111) { return R.drawable.p111a; }
        if (pokemonId == 112) { return R.drawable.p112a; }
        if (pokemonId == 113) { return R.drawable.p113a; }
        if (pokemonId == 114) { return R.drawable.p114a; }
        if (pokemonId == 115) { return R.drawable.p115a; }
        if (pokemonId == 115) { return R.drawable.p115a; }
        if (pokemonId == 116) { return R.drawable.p116a; }
        if (pokemonId == 117) { return R.drawable.p117a; }
        if (pokemonId == 118) { return R.drawable.p118a; }
        if (pokemonId == 119) { return R.drawable.p119a; }
        if (pokemonId == 120) { return R.drawable.p120a; }
        if (pokemonId == 121) { return R.drawable.p121a; }
        if (pokemonId == 122) { return R.drawable.p122a; }
        if (pokemonId == 123) { return R.drawable.p123a; }
        if (pokemonId == 124) { return R.drawable.p124a; }
        if (pokemonId == 125) { return R.drawable.p125a; }
        if (pokemonId == 126) { return R.drawable.p126a; }
        if (pokemonId == 127) { return R.drawable.p127a; }
        if (pokemonId == 127) { return R.drawable.p127a; }
        if (pokemonId == 128) { return R.drawable.p128a; }
        if (pokemonId == 129) { return R.drawable.p129a; }
        if (pokemonId == 130) { return R.drawable.p130a; }
        if (pokemonId == 130) { return R.drawable.p130a; }
        if (pokemonId == 131) { return R.drawable.p131a; }
        if (pokemonId == 132) { return R.drawable.p132a; }
        if (pokemonId == 133) { return R.drawable.p133a; }
        if (pokemonId == 134) { return R.drawable.p134a; }
        if (pokemonId == 135) { return R.drawable.p135a; }
        if (pokemonId == 136) { return R.drawable.p136a; }
        if (pokemonId == 137) { return R.drawable.p137a; }
        if (pokemonId == 138) { return R.drawable.p138a; }
        if (pokemonId == 139) { return R.drawable.p139a; }
        if (pokemonId == 140) { return R.drawable.p140a; }
        if (pokemonId == 141) { return R.drawable.p141a; }
        if (pokemonId == 142) { return R.drawable.p142a; }
        if (pokemonId == 142) { return R.drawable.p142a; }
        if (pokemonId == 143) { return R.drawable.p143a; }
        if (pokemonId == 144) { return R.drawable.p144a; }
        if (pokemonId == 145) { return R.drawable.p145a; }
        if (pokemonId == 146) { return R.drawable.p146a; }
        if (pokemonId == 147) { return R.drawable.p147a; }
        if (pokemonId == 148) { return R.drawable.p148a; }
        if (pokemonId == 149) { return R.drawable.p149a; }
        if (pokemonId == 150) { return R.drawable.p150a; }
        if (pokemonId == 150) { return R.drawable.p150a; }
        if (pokemonId == 150) { return R.drawable.p150a; }
        if (pokemonId == 151) { return R.drawable.p151a; }
        if (pokemonId == 152) { return R.drawable.p152a; }
        if (pokemonId == 153) { return R.drawable.p153a; }
        if (pokemonId == 154) { return R.drawable.p154a; }
        if (pokemonId == 155) { return R.drawable.p155a; }
        if (pokemonId == 156) { return R.drawable.p156a; }
        if (pokemonId == 157) { return R.drawable.p157a; }
        if (pokemonId == 158) { return R.drawable.p158a; }
        if (pokemonId == 159) { return R.drawable.p159a; }
        if (pokemonId == 160) { return R.drawable.p160a; }
        if (pokemonId == 161) { return R.drawable.p161a; }
        if (pokemonId == 162) { return R.drawable.p162a; }
        if (pokemonId == 163) { return R.drawable.p163a; }
        if (pokemonId == 164) { return R.drawable.p164a; }
        if (pokemonId == 165) { return R.drawable.p165a; }
        if (pokemonId == 166) { return R.drawable.p166a; }
        if (pokemonId == 167) { return R.drawable.p167a; }
        if (pokemonId == 168) { return R.drawable.p168a; }
        if (pokemonId == 169) { return R.drawable.p169a; }
        if (pokemonId == 170) { return R.drawable.p170a; }
        if (pokemonId == 171) { return R.drawable.p171a; }
        if (pokemonId == 172) { return R.drawable.p172a; }
        if (pokemonId == 173) { return R.drawable.p173a; }
        if (pokemonId == 174) { return R.drawable.p174a; }
        if (pokemonId == 175) { return R.drawable.p175a; }
        if (pokemonId == 176) { return R.drawable.p176a; }
        if (pokemonId == 177) { return R.drawable.p177a; }
        if (pokemonId == 178) { return R.drawable.p178a; }
        if (pokemonId == 179) { return R.drawable.p179a; }
        if (pokemonId == 180) { return R.drawable.p180a; }
        if (pokemonId == 181) { return R.drawable.p181a; }
        if (pokemonId == 181) { return R.drawable.p181a; }
        if (pokemonId == 182) { return R.drawable.p182a; }
        if (pokemonId == 183) { return R.drawable.p183a; }
        if (pokemonId == 184) { return R.drawable.p184a; }
        if (pokemonId == 185) { return R.drawable.p185a; }
        if (pokemonId == 186) { return R.drawable.p186a; }
        if (pokemonId == 187) { return R.drawable.p187a; }
        if (pokemonId == 188) { return R.drawable.p188a; }
        if (pokemonId == 189) { return R.drawable.p189a; }
        if (pokemonId == 190) { return R.drawable.p190a; }
        if (pokemonId == 191) { return R.drawable.p191a; }
        if (pokemonId == 192) { return R.drawable.p192a; }
        if (pokemonId == 193) { return R.drawable.p193a; }
        if (pokemonId == 194) { return R.drawable.p194a; }
        if (pokemonId == 195) { return R.drawable.p195a; }
        if (pokemonId == 196) { return R.drawable.p196a; }
        if (pokemonId == 197) { return R.drawable.p197a; }
        if (pokemonId == 198) { return R.drawable.p198a; }
        if (pokemonId == 199) { return R.drawable.p199a; }
        if (pokemonId == 200) { return R.drawable.p200a; }
        if (pokemonId == 201) { return R.drawable.p201a; }
        if (pokemonId == 202) { return R.drawable.p202a; }
        if (pokemonId == 203) { return R.drawable.p203a; }
        if (pokemonId == 204) { return R.drawable.p204a; }
        if (pokemonId == 205) { return R.drawable.p205a; }
        if (pokemonId == 206) { return R.drawable.p206a; }
        if (pokemonId == 207) { return R.drawable.p207a; }
        if (pokemonId == 208) { return R.drawable.p208a; }
        if (pokemonId == 208) { return R.drawable.p208a; }
        if (pokemonId == 209) { return R.drawable.p209a; }
        if (pokemonId == 210) { return R.drawable.p210a; }
        if (pokemonId == 211) { return R.drawable.p211a; }
        if (pokemonId == 212) { return R.drawable.p212a; }
        if (pokemonId == 212) { return R.drawable.p212a; }
        if (pokemonId == 213) { return R.drawable.p213a; }
        if (pokemonId == 214) { return R.drawable.p214a; }
        if (pokemonId == 214) { return R.drawable.p214a; }
        if (pokemonId == 215) { return R.drawable.p215a; }
        if (pokemonId == 216) { return R.drawable.p216a; }
        if (pokemonId == 217) { return R.drawable.p217a; }
        if (pokemonId == 218) { return R.drawable.p218a; }
        if (pokemonId == 219) { return R.drawable.p219a; }
        if (pokemonId == 220) { return R.drawable.p220a; }
        if (pokemonId == 221) { return R.drawable.p221a; }
        if (pokemonId == 222) { return R.drawable.p222a; }
        if (pokemonId == 223) { return R.drawable.p223a; }
        if (pokemonId == 224) { return R.drawable.p224a; }
        if (pokemonId == 225) { return R.drawable.p225a; }
        if (pokemonId == 226) { return R.drawable.p226a; }
        if (pokemonId == 227) { return R.drawable.p227a; }
        if (pokemonId == 228) { return R.drawable.p228a; }
        if (pokemonId == 229) { return R.drawable.p229a; }
        if (pokemonId == 229) { return R.drawable.p229a; }
        if (pokemonId == 230) { return R.drawable.p230a; }
        if (pokemonId == 231) { return R.drawable.p231a; }
        if (pokemonId == 232) { return R.drawable.p232a; }
        if (pokemonId == 233) { return R.drawable.p233a; }
        if (pokemonId == 234) { return R.drawable.p234a; }
        if (pokemonId == 235) { return R.drawable.p235a; }
        if (pokemonId == 236) { return R.drawable.p236a; }
        if (pokemonId == 237) { return R.drawable.p237a; }
        if (pokemonId == 238) { return R.drawable.p238a; }
        if (pokemonId == 239) { return R.drawable.p239a; }
        if (pokemonId == 240) { return R.drawable.p240a; }
        if (pokemonId == 241) { return R.drawable.p241a; }
        if (pokemonId == 242) { return R.drawable.p242a; }
        if (pokemonId == 243) { return R.drawable.p243a; }
        if (pokemonId == 244) { return R.drawable.p244a; }
        if (pokemonId == 245) { return R.drawable.p245a; }
        if (pokemonId == 246) { return R.drawable.p246a; }
        if (pokemonId == 247) { return R.drawable.p247a; }
        if (pokemonId == 248) { return R.drawable.p248a; }
        if (pokemonId == 248) { return R.drawable.p248a; }
        if (pokemonId == 249) { return R.drawable.p249a; }
        if (pokemonId == 250) { return R.drawable.p250a; }
        if (pokemonId == 251) { return R.drawable.p251a; }
        if (pokemonId == 252) { return R.drawable.p252a; }
        if (pokemonId == 253) { return R.drawable.p253a; }
        if (pokemonId == 254) { return R.drawable.p254a; }
        if (pokemonId == 254) { return R.drawable.p254a; }
        if (pokemonId == 255) { return R.drawable.p255a; }
        if (pokemonId == 256) { return R.drawable.p256a; }
        if (pokemonId == 257) { return R.drawable.p257a; }
        if (pokemonId == 257) { return R.drawable.p257a; }
        if (pokemonId == 258) { return R.drawable.p258a; }
        if (pokemonId == 259) { return R.drawable.p259a; }
        if (pokemonId == 260) { return R.drawable.p260a; }
        if (pokemonId == 260) { return R.drawable.p260a; }
        if (pokemonId == 261) { return R.drawable.p261a; }
        if (pokemonId == 262) { return R.drawable.p262a; }
        if (pokemonId == 263) { return R.drawable.p263a; }
        if (pokemonId == 264) { return R.drawable.p264a; }
        if (pokemonId == 265) { return R.drawable.p265a; }
        if (pokemonId == 266) { return R.drawable.p266a; }
        if (pokemonId == 267) { return R.drawable.p267a; }
        if (pokemonId == 268) { return R.drawable.p268a; }
        if (pokemonId == 269) { return R.drawable.p269a; }
        if (pokemonId == 270) { return R.drawable.p270a; }
        if (pokemonId == 271) { return R.drawable.p271a; }
        if (pokemonId == 272) { return R.drawable.p272a; }
        if (pokemonId == 273) { return R.drawable.p273a; }
        if (pokemonId == 274) { return R.drawable.p274a; }
        if (pokemonId == 275) { return R.drawable.p275a; }
        if (pokemonId == 276) { return R.drawable.p276a; }
        if (pokemonId == 277) { return R.drawable.p277a; }
        if (pokemonId == 278) { return R.drawable.p278a; }
        if (pokemonId == 279) { return R.drawable.p279a; }
        if (pokemonId == 280) { return R.drawable.p280a; }
        if (pokemonId == 281) { return R.drawable.p281a; }
        if (pokemonId == 282) { return R.drawable.p282a; }
        if (pokemonId == 282) { return R.drawable.p282a; }
        if (pokemonId == 283) { return R.drawable.p283a; }
        if (pokemonId == 284) { return R.drawable.p284a; }
        if (pokemonId == 285) { return R.drawable.p285a; }
        if (pokemonId == 286) { return R.drawable.p286a; }
        if (pokemonId == 287) { return R.drawable.p287a; }
        if (pokemonId == 288) { return R.drawable.p288a; }
        if (pokemonId == 289) { return R.drawable.p289a; }
        if (pokemonId == 290) { return R.drawable.p290a; }
        if (pokemonId == 291) { return R.drawable.p291a; }
        if (pokemonId == 292) { return R.drawable.p292a; }
        if (pokemonId == 293) { return R.drawable.p293a; }
        if (pokemonId == 294) { return R.drawable.p294a; }
        if (pokemonId == 295) { return R.drawable.p295a; }
        if (pokemonId == 296) { return R.drawable.p296a; }
        if (pokemonId == 297) { return R.drawable.p297a; }
        if (pokemonId == 298) { return R.drawable.p298a; }
        if (pokemonId == 299) { return R.drawable.p299a; }
        if (pokemonId == 300) { return R.drawable.p300a; }
        if (pokemonId == 301) { return R.drawable.p301a; }
        if (pokemonId == 302) { return R.drawable.p302a; }
        if (pokemonId == 302) { return R.drawable.p302a; }
        if (pokemonId == 303) { return R.drawable.p303a; }
        if (pokemonId == 303) { return R.drawable.p303a; }
        if (pokemonId == 304) { return R.drawable.p304a; }
        if (pokemonId == 305) { return R.drawable.p305a; }
        if (pokemonId == 306) { return R.drawable.p306a; }
        if (pokemonId == 306) { return R.drawable.p306a; }
        if (pokemonId == 307) { return R.drawable.p307a; }
        if (pokemonId == 308) { return R.drawable.p308a; }
        if (pokemonId == 308) { return R.drawable.p308a; }
        if (pokemonId == 309) { return R.drawable.p309a; }
        if (pokemonId == 310) { return R.drawable.p310a; }
        if (pokemonId == 310) { return R.drawable.p310a; }
        if (pokemonId == 311) { return R.drawable.p311a; }
        if (pokemonId == 312) { return R.drawable.p312a; }
        if (pokemonId == 313) { return R.drawable.p313a; }
        if (pokemonId == 314) { return R.drawable.p314a; }
        if (pokemonId == 315) { return R.drawable.p315a; }
        if (pokemonId == 316) { return R.drawable.p316a; }
        if (pokemonId == 317) { return R.drawable.p317a; }
        if (pokemonId == 318) { return R.drawable.p318a; }
        if (pokemonId == 319) { return R.drawable.p319a; }
        if (pokemonId == 319) { return R.drawable.p319a; }
        if (pokemonId == 320) { return R.drawable.p320a; }
        if (pokemonId == 321) { return R.drawable.p321a; }
        if (pokemonId == 322) { return R.drawable.p322a; }
        if (pokemonId == 323) { return R.drawable.p323a; }
        if (pokemonId == 323) { return R.drawable.p323a; }
        if (pokemonId == 324) { return R.drawable.p324a; }
        if (pokemonId == 325) { return R.drawable.p325a; }
        if (pokemonId == 326) { return R.drawable.p326a; }
        if (pokemonId == 327) { return R.drawable.p327a; }
        if (pokemonId == 328) { return R.drawable.p328a; }
        if (pokemonId == 329) { return R.drawable.p329a; }
        if (pokemonId == 330) { return R.drawable.p330a; }
        if (pokemonId == 331) { return R.drawable.p331a; }
        if (pokemonId == 332) { return R.drawable.p332a; }
        if (pokemonId == 333) { return R.drawable.p333a; }
        if (pokemonId == 334) { return R.drawable.p334a; }
        if (pokemonId == 334) { return R.drawable.p334a; }
        if (pokemonId == 335) { return R.drawable.p335a; }
        if (pokemonId == 336) { return R.drawable.p336a; }
        if (pokemonId == 337) { return R.drawable.p337a; }
        if (pokemonId == 338) { return R.drawable.p338a; }
        if (pokemonId == 339) { return R.drawable.p339a; }
        if (pokemonId == 340) { return R.drawable.p340a; }
        if (pokemonId == 341) { return R.drawable.p341a; }
        if (pokemonId == 342) { return R.drawable.p342a; }
        if (pokemonId == 343) { return R.drawable.p343a; }
        if (pokemonId == 344) { return R.drawable.p344a; }
        if (pokemonId == 345) { return R.drawable.p345a; }
        if (pokemonId == 346) { return R.drawable.p346a; }
        if (pokemonId == 347) { return R.drawable.p347a; }
        if (pokemonId == 348) { return R.drawable.p348a; }
        if (pokemonId == 349) { return R.drawable.p349a; }
        if (pokemonId == 350) { return R.drawable.p350a; }
        if (pokemonId == 351) { return R.drawable.p351a; }
        if (pokemonId == 351) { return R.drawable.p351a; }
        if (pokemonId == 351) { return R.drawable.p351a; }
        if (pokemonId == 351) { return R.drawable.p351a; }
        if (pokemonId == 352) { return R.drawable.p352a; }
        if (pokemonId == 353) { return R.drawable.p353a; }
        if (pokemonId == 354) { return R.drawable.p354a; }
        if (pokemonId == 354) { return R.drawable.p354a; }
        if (pokemonId == 355) { return R.drawable.p355a; }
        if (pokemonId == 356) { return R.drawable.p356a; }
        if (pokemonId == 357) { return R.drawable.p357a; }
        if (pokemonId == 358) { return R.drawable.p358a; }
        if (pokemonId == 359) { return R.drawable.p359a; }
        if (pokemonId == 359) { return R.drawable.p359a; }
        if (pokemonId == 360) { return R.drawable.p360a; }
        if (pokemonId == 361) { return R.drawable.p361a; }
        if (pokemonId == 362) { return R.drawable.p362a; }
        if (pokemonId == 362) { return R.drawable.p362a; }
        if (pokemonId == 363) { return R.drawable.p363a; }
        if (pokemonId == 364) { return R.drawable.p364a; }
        if (pokemonId == 365) { return R.drawable.p365a; }
        if (pokemonId == 366) { return R.drawable.p366a; }
        if (pokemonId == 367) { return R.drawable.p367a; }
        if (pokemonId == 368) { return R.drawable.p368a; }
        if (pokemonId == 369) { return R.drawable.p369a; }
        if (pokemonId == 370) { return R.drawable.p370a; }
        if (pokemonId == 371) { return R.drawable.p371a; }
        if (pokemonId == 372) { return R.drawable.p372a; }
        if (pokemonId == 373) { return R.drawable.p373a; }
        if (pokemonId == 373) { return R.drawable.p373a; }
        if (pokemonId == 374) { return R.drawable.p374a; }
        if (pokemonId == 375) { return R.drawable.p375a; }
        if (pokemonId == 376) { return R.drawable.p376a; }
        if (pokemonId == 376) { return R.drawable.p376a; }
        if (pokemonId == 377) { return R.drawable.p377a; }
        if (pokemonId == 378) { return R.drawable.p378a; }
        if (pokemonId == 379) { return R.drawable.p379a; }
        if (pokemonId == 380) { return R.drawable.p380a; }
        if (pokemonId == 380) { return R.drawable.p380a; }
        if (pokemonId == 381) { return R.drawable.p381a; }
        if (pokemonId == 381) { return R.drawable.p381a; }
        if (pokemonId == 382) { return R.drawable.p382a; }
        if (pokemonId == 382) { return R.drawable.p382a; }
        if (pokemonId == 383) { return R.drawable.p383a; }
        if (pokemonId == 383) { return R.drawable.p383a; }
        if (pokemonId == 384) { return R.drawable.p384a; }
        if (pokemonId == 384) { return R.drawable.p384a; }
        if (pokemonId == 385) { return R.drawable.p385a; }
        if (pokemonId == 386) { return R.drawable.p386a; }
        if (pokemonId == 386) { return R.drawable.p386a; }
        if (pokemonId == 386) { return R.drawable.p386a; }
        if (pokemonId == 386) { return R.drawable.p386a; }
        if (pokemonId == 387) { return R.drawable.p387a; }
        if (pokemonId == 388) { return R.drawable.p388a; }
        if (pokemonId == 389) { return R.drawable.p389a; }
        if (pokemonId == 390) { return R.drawable.p390a; }
        if (pokemonId == 391) { return R.drawable.p391a; }
        if (pokemonId == 392) { return R.drawable.p392a; }
        if (pokemonId == 393) { return R.drawable.p393a; }
        if (pokemonId == 394) { return R.drawable.p394a; }
        if (pokemonId == 395) { return R.drawable.p395a; }
        if (pokemonId == 396) { return R.drawable.p396a; }
        if (pokemonId == 397) { return R.drawable.p397a; }
        if (pokemonId == 398) { return R.drawable.p398a; }
        if (pokemonId == 399) { return R.drawable.p399a; }
        if (pokemonId == 400) { return R.drawable.p400a; }
        if (pokemonId == 401) { return R.drawable.p401a; }
        if (pokemonId == 402) { return R.drawable.p402a; }
        if (pokemonId == 403) { return R.drawable.p403a; }
        if (pokemonId == 404) { return R.drawable.p404a; }
        if (pokemonId == 405) { return R.drawable.p405a; }
        if (pokemonId == 406) { return R.drawable.p406a; }
        if (pokemonId == 407) { return R.drawable.p407a; }
        if (pokemonId == 408) { return R.drawable.p408a; }
        if (pokemonId == 409) { return R.drawable.p409a; }
        if (pokemonId == 410) { return R.drawable.p410a; }
        if (pokemonId == 411) { return R.drawable.p411a; }
        if (pokemonId == 412) { return R.drawable.p412a; }
        if (pokemonId == 413) { return R.drawable.p413a; }
        if (pokemonId == 413) { return R.drawable.p413a; }
        if (pokemonId == 413) { return R.drawable.p413a; }
        if (pokemonId == 414) { return R.drawable.p414a; }
        if (pokemonId == 415) { return R.drawable.p415a; }
        if (pokemonId == 416) { return R.drawable.p416a; }
        if (pokemonId == 417) { return R.drawable.p417a; }
        if (pokemonId == 418) { return R.drawable.p418a; }
        if (pokemonId == 419) { return R.drawable.p419a; }
        if (pokemonId == 420) { return R.drawable.p420a; }
        if (pokemonId == 421) { return R.drawable.p421a; }
        if (pokemonId == 422) { return R.drawable.p422a; }
        if (pokemonId == 423) { return R.drawable.p423a; }
        if (pokemonId == 424) { return R.drawable.p424a; }
        if (pokemonId == 425) { return R.drawable.p425a; }
        if (pokemonId == 426) { return R.drawable.p426a; }
        if (pokemonId == 427) { return R.drawable.p427a; }
        if (pokemonId == 428) { return R.drawable.p428a; }
        if (pokemonId == 428) { return R.drawable.p428a; }
        if (pokemonId == 429) { return R.drawable.p429a; }
        if (pokemonId == 430) { return R.drawable.p430a; }
        if (pokemonId == 431) { return R.drawable.p431a; }
        if (pokemonId == 432) { return R.drawable.p432a; }
        if (pokemonId == 433) { return R.drawable.p433a; }
        if (pokemonId == 434) { return R.drawable.p434a; }
        if (pokemonId == 435) { return R.drawable.p435a; }
        if (pokemonId == 436) { return R.drawable.p436a; }
        if (pokemonId == 437) { return R.drawable.p437a; }
        if (pokemonId == 438) { return R.drawable.p438a; }
        if (pokemonId == 439) { return R.drawable.p439a; }
        if (pokemonId == 440) { return R.drawable.p440a; }
        if (pokemonId == 441) { return R.drawable.p441a; }
        if (pokemonId == 442) { return R.drawable.p442a; }
        if (pokemonId == 443) { return R.drawable.p443a; }
        if (pokemonId == 444) { return R.drawable.p444a; }
        if (pokemonId == 445) { return R.drawable.p445a; }
        if (pokemonId == 445) { return R.drawable.p445a; }
        if (pokemonId == 446) { return R.drawable.p446a; }
        if (pokemonId == 447) { return R.drawable.p447a; }
        if (pokemonId == 448) { return R.drawable.p448a; }
        if (pokemonId == 448) { return R.drawable.p448a; }
        if (pokemonId == 449) { return R.drawable.p449a; }
        if (pokemonId == 450) { return R.drawable.p450a; }
        if (pokemonId == 451) { return R.drawable.p451a; }
        if (pokemonId == 452) { return R.drawable.p452a; }
        if (pokemonId == 453) { return R.drawable.p453a; }
        if (pokemonId == 454) { return R.drawable.p454a; }
        if (pokemonId == 455) { return R.drawable.p455a; }
        if (pokemonId == 456) { return R.drawable.p456a; }
        if (pokemonId == 457) { return R.drawable.p457a; }
        if (pokemonId == 458) { return R.drawable.p458a; }
        if (pokemonId == 459) { return R.drawable.p459a; }
        if (pokemonId == 460) { return R.drawable.p460a; }
        if (pokemonId == 460) { return R.drawable.p460a; }
        if (pokemonId == 461) { return R.drawable.p461a; }
        if (pokemonId == 462) { return R.drawable.p462a; }
        if (pokemonId == 463) { return R.drawable.p463a; }
        if (pokemonId == 464) { return R.drawable.p464a; }
        if (pokemonId == 465) { return R.drawable.p465a; }
        if (pokemonId == 466) { return R.drawable.p466a; }
        if (pokemonId == 467) { return R.drawable.p467a; }
        if (pokemonId == 468) { return R.drawable.p468a; }
        if (pokemonId == 469) { return R.drawable.p469a; }
        if (pokemonId == 470) { return R.drawable.p470a; }
        if (pokemonId == 471) { return R.drawable.p471a; }
        if (pokemonId == 472) { return R.drawable.p472a; }
        if (pokemonId == 473) { return R.drawable.p473a; }
        if (pokemonId == 474) { return R.drawable.p474a; }
        if (pokemonId == 475) { return R.drawable.p475a; }
        if (pokemonId == 475) { return R.drawable.p475a; }
        if (pokemonId == 476) { return R.drawable.p476a; }
        if (pokemonId == 477) { return R.drawable.p477a; }
        if (pokemonId == 478) { return R.drawable.p478a; }
        if (pokemonId == 479) { return R.drawable.p479a; }
        if (pokemonId == 479) { return R.drawable.p479a; }
        if (pokemonId == 479) { return R.drawable.p479a; }
        if (pokemonId == 479) { return R.drawable.p479a; }
        if (pokemonId == 479) { return R.drawable.p479a; }
        if (pokemonId == 479) { return R.drawable.p479a; }
        if (pokemonId == 480) { return R.drawable.p480a; }
        if (pokemonId == 481) { return R.drawable.p481a; }
        if (pokemonId == 482) { return R.drawable.p482a; }
        if (pokemonId == 483) { return R.drawable.p483a; }
        if (pokemonId == 484) { return R.drawable.p484a; }
        if (pokemonId == 485) { return R.drawable.p485a; }
        if (pokemonId == 486) { return R.drawable.p486a; }
        if (pokemonId == 487) { return R.drawable.p487a; }
        if (pokemonId == 487) { return R.drawable.p487a; }
        if (pokemonId == 488) { return R.drawable.p488a; }
        if (pokemonId == 489) { return R.drawable.p489a; }
        if (pokemonId == 490) { return R.drawable.p490a; }
        if (pokemonId == 491) { return R.drawable.p491a; }
        if (pokemonId == 492) { return R.drawable.p492a; }
        if (pokemonId == 492) { return R.drawable.p492a; }
        if (pokemonId == 493) { return R.drawable.p493a; }
        if (pokemonId == 494) { return R.drawable.p494a; }
        if (pokemonId == 495) { return R.drawable.p495a; }
        if (pokemonId == 496) { return R.drawable.p496a; }
        if (pokemonId == 497) { return R.drawable.p497a; }
        if (pokemonId == 498) { return R.drawable.p498a; }
        if (pokemonId == 499) { return R.drawable.p499a; }
        if (pokemonId == 500) { return R.drawable.p500a; }
        if (pokemonId == 501) { return R.drawable.p501a; }
        if (pokemonId == 502) { return R.drawable.p502a; }
        if (pokemonId == 503) { return R.drawable.p503a; }
        if (pokemonId == 504) { return R.drawable.p504a; }
        if (pokemonId == 505) { return R.drawable.p505a; }
        if (pokemonId == 506) { return R.drawable.p506a; }
        if (pokemonId == 507) { return R.drawable.p507a; }
        if (pokemonId == 508) { return R.drawable.p508a; }
        if (pokemonId == 509) { return R.drawable.p509a; }
        if (pokemonId == 510) { return R.drawable.p510a; }
        if (pokemonId == 511) { return R.drawable.p511a; }
        if (pokemonId == 512) { return R.drawable.p512a; }
        if (pokemonId == 513) { return R.drawable.p513a; }
        if (pokemonId == 514) { return R.drawable.p514a; }
        if (pokemonId == 515) { return R.drawable.p515a; }
        if (pokemonId == 516) { return R.drawable.p516a; }
        if (pokemonId == 517) { return R.drawable.p517a; }
        if (pokemonId == 518) { return R.drawable.p518a; }
        if (pokemonId == 519) { return R.drawable.p519a; }
        if (pokemonId == 520) { return R.drawable.p520a; }
        if (pokemonId == 521) { return R.drawable.p521a; }
        if (pokemonId == 522) { return R.drawable.p522a; }
        if (pokemonId == 523) { return R.drawable.p523a; }
        if (pokemonId == 524) { return R.drawable.p524a; }
        if (pokemonId == 525) { return R.drawable.p525a; }
        if (pokemonId == 526) { return R.drawable.p526a; }
        if (pokemonId == 527) { return R.drawable.p527a; }
        if (pokemonId == 528) { return R.drawable.p528a; }
        if (pokemonId == 529) { return R.drawable.p529a; }
        if (pokemonId == 530) { return R.drawable.p530a; }
        if (pokemonId == 531) { return R.drawable.p531a; }
        if (pokemonId == 531) { return R.drawable.p531a; }
        if (pokemonId == 532) { return R.drawable.p532a; }
        if (pokemonId == 533) { return R.drawable.p533a; }
        if (pokemonId == 534) { return R.drawable.p534a; }
        if (pokemonId == 535) { return R.drawable.p535a; }
        if (pokemonId == 536) { return R.drawable.p536a; }
        if (pokemonId == 537) { return R.drawable.p537a; }
        if (pokemonId == 538) { return R.drawable.p538a; }
        if (pokemonId == 539) { return R.drawable.p539a; }
        if (pokemonId == 540) { return R.drawable.p540a; }
        if (pokemonId == 541) { return R.drawable.p541a; }
        if (pokemonId == 542) { return R.drawable.p542a; }
        if (pokemonId == 543) { return R.drawable.p543a; }
        if (pokemonId == 544) { return R.drawable.p544a; }
        if (pokemonId == 545) { return R.drawable.p545a; }
        if (pokemonId == 546) { return R.drawable.p546a; }
        if (pokemonId == 547) { return R.drawable.p547a; }
        if (pokemonId == 548) { return R.drawable.p548a; }
        if (pokemonId == 549) { return R.drawable.p549a; }
        if (pokemonId == 550) { return R.drawable.p550a; }
        if (pokemonId == 550) { return R.drawable.p550a; }
        if (pokemonId == 551) { return R.drawable.p551a; }
        if (pokemonId == 552) { return R.drawable.p552a; }
        if (pokemonId == 553) { return R.drawable.p553a; }
        if (pokemonId == 554) { return R.drawable.p554a; }
        if (pokemonId == 555) { return R.drawable.p555a; }
        if (pokemonId == 555) { return R.drawable.p555a; }
        if (pokemonId == 556) { return R.drawable.p556a; }
        if (pokemonId == 557) { return R.drawable.p557a; }
        if (pokemonId == 558) { return R.drawable.p558a; }
        if (pokemonId == 559) { return R.drawable.p559a; }
        if (pokemonId == 560) { return R.drawable.p560a; }
        if (pokemonId == 561) { return R.drawable.p561a; }
        if (pokemonId == 562) { return R.drawable.p562a; }
        if (pokemonId == 563) { return R.drawable.p563a; }
        if (pokemonId == 564) { return R.drawable.p564a; }
        if (pokemonId == 565) { return R.drawable.p565a; }
        if (pokemonId == 566) { return R.drawable.p566a; }
        if (pokemonId == 567) { return R.drawable.p567a; }
        if (pokemonId == 568) { return R.drawable.p568a; }
        if (pokemonId == 569) { return R.drawable.p569a; }
        if (pokemonId == 570) { return R.drawable.p570a; }
        if (pokemonId == 571) { return R.drawable.p571a; }
        if (pokemonId == 572) { return R.drawable.p572a; }
        if (pokemonId == 573) { return R.drawable.p573a; }
        if (pokemonId == 574) { return R.drawable.p574a; }
        if (pokemonId == 575) { return R.drawable.p575a; }
        if (pokemonId == 576) { return R.drawable.p576a; }
        if (pokemonId == 577) { return R.drawable.p577a; }
        if (pokemonId == 578) { return R.drawable.p578a; }
        if (pokemonId == 579) { return R.drawable.p579a; }
        if (pokemonId == 580) { return R.drawable.p580a; }
        if (pokemonId == 581) { return R.drawable.p581a; }
        if (pokemonId == 582) { return R.drawable.p582a; }
        if (pokemonId == 583) { return R.drawable.p583a; }
        if (pokemonId == 584) { return R.drawable.p584a; }
        if (pokemonId == 585) { return R.drawable.p585a; }
        if (pokemonId == 586) { return R.drawable.p586a; }
        if (pokemonId == 587) { return R.drawable.p587a; }
        if (pokemonId == 588) { return R.drawable.p588a; }
        if (pokemonId == 589) { return R.drawable.p589a; }
        if (pokemonId == 590) { return R.drawable.p590a; }
        if (pokemonId == 591) { return R.drawable.p591a; }
        if (pokemonId == 592) { return R.drawable.p592a; }
        if (pokemonId == 593) { return R.drawable.p593a; }
        if (pokemonId == 594) { return R.drawable.p594a; }
        if (pokemonId == 595) { return R.drawable.p595a; }
        if (pokemonId == 596) { return R.drawable.p596a; }
        if (pokemonId == 597) { return R.drawable.p597a; }
        if (pokemonId == 598) { return R.drawable.p598a; }
        if (pokemonId == 599) { return R.drawable.p599a; }
        if (pokemonId == 600) { return R.drawable.p600a; }
        if (pokemonId == 601) { return R.drawable.p601a; }
        if (pokemonId == 602) { return R.drawable.p602a; }
        if (pokemonId == 603) { return R.drawable.p603a; }
        if (pokemonId == 604) { return R.drawable.p604a; }
        if (pokemonId == 605) { return R.drawable.p605a; }
        if (pokemonId == 606) { return R.drawable.p606a; }
        if (pokemonId == 607) { return R.drawable.p607a; }
        if (pokemonId == 608) { return R.drawable.p608a; }
        if (pokemonId == 609) { return R.drawable.p609a; }
        if (pokemonId == 610) { return R.drawable.p610a; }
        if (pokemonId == 611) { return R.drawable.p611a; }
        if (pokemonId == 612) { return R.drawable.p612a; }
        if (pokemonId == 613) { return R.drawable.p613a; }
        if (pokemonId == 614) { return R.drawable.p614a; }
        if (pokemonId == 615) { return R.drawable.p615a; }
        if (pokemonId == 616) { return R.drawable.p616a; }
        if (pokemonId == 617) { return R.drawable.p617a; }
        if (pokemonId == 618) { return R.drawable.p618a; }
        if (pokemonId == 619) { return R.drawable.p619a; }
        if (pokemonId == 620) { return R.drawable.p620a; }
        if (pokemonId == 621) { return R.drawable.p621a; }
        if (pokemonId == 622) { return R.drawable.p622a; }
        if (pokemonId == 623) { return R.drawable.p623a; }
        if (pokemonId == 624) { return R.drawable.p624a; }
        if (pokemonId == 625) { return R.drawable.p625a; }
        if (pokemonId == 626) { return R.drawable.p626a; }
        if (pokemonId == 627) { return R.drawable.p627a; }
        if (pokemonId == 628) { return R.drawable.p628a; }
        if (pokemonId == 629) { return R.drawable.p629a; }
        if (pokemonId == 630) { return R.drawable.p630a; }
        if (pokemonId == 631) { return R.drawable.p631a; }
        if (pokemonId == 632) { return R.drawable.p632a; }
        if (pokemonId == 633) { return R.drawable.p633a; }
        if (pokemonId == 634) { return R.drawable.p634a; }
        if (pokemonId == 635) { return R.drawable.p635a; }
        if (pokemonId == 636) { return R.drawable.p636a; }
        if (pokemonId == 637) { return R.drawable.p637a; }
        if (pokemonId == 638) { return R.drawable.p638a; }
        if (pokemonId == 639) { return R.drawable.p639a; }
        if (pokemonId == 640) { return R.drawable.p640a; }
        if (pokemonId == 641) { return R.drawable.p641a; }
        if (pokemonId == 641) { return R.drawable.p641a; }
        if (pokemonId == 642) { return R.drawable.p642a; }
        if (pokemonId == 642) { return R.drawable.p642a; }
        if (pokemonId == 643) { return R.drawable.p643a; }
        if (pokemonId == 644) { return R.drawable.p644a; }
        if (pokemonId == 645) { return R.drawable.p645a; }
        if (pokemonId == 645) { return R.drawable.p645a; }
        if (pokemonId == 646) { return R.drawable.p646a; }
        if (pokemonId == 646) { return R.drawable.p646a; }
        if (pokemonId == 646) { return R.drawable.p646a; }
        if (pokemonId == 647) { return R.drawable.p647resolute_forma; }
        if (pokemonId == 647) { return R.drawable.p647standard_forma; }
        if (pokemonId == 648) { return R.drawable.p648a; }
        if (pokemonId == 648) { return R.drawable.p648a; }
        if (pokemonId == 649) { return R.drawable.p649a; }
        if (pokemonId == 650) { return R.drawable.p650a; }
        if (pokemonId == 651) { return R.drawable.p651a; }
        if (pokemonId == 652) { return R.drawable.p652a; }
        if (pokemonId == 653) { return R.drawable.p653a; }
        if (pokemonId == 654) { return R.drawable.p654a; }
        if (pokemonId == 655) { return R.drawable.p655a; }
        if (pokemonId == 656) { return R.drawable.p656a; }
        if (pokemonId == 657) { return R.drawable.p657a; }
        if (pokemonId == 658) { return R.drawable.p658a; }
        if (pokemonId == 659) { return R.drawable.p659a; }
        if (pokemonId == 660) { return R.drawable.p660a; }
        if (pokemonId == 661) { return R.drawable.p661a; }
        if (pokemonId == 662) { return R.drawable.p662a; }
        if (pokemonId == 663) { return R.drawable.p663a; }
        if (pokemonId == 664) { return R.drawable.p664a; }
        if (pokemonId == 665) { return R.drawable.p665a; }
        if (pokemonId == 666) { return R.drawable.p666a; }
        if (pokemonId == 667) { return R.drawable.p667a; }
        if (pokemonId == 668) { return R.drawable.p668a; }
        if (pokemonId == 669) { return R.drawable.p669a; }
        if (pokemonId == 670) { return R.drawable.p670a; }
        if (pokemonId == 670) { return R.drawable.p670a; }
        if (pokemonId == 671) { return R.drawable.p671a; }
        if (pokemonId == 672) { return R.drawable.p672a; }
        if (pokemonId == 673) { return R.drawable.p673a; }
        if (pokemonId == 674) { return R.drawable.p674a; }
        if (pokemonId == 675) { return R.drawable.p675a; }
        if (pokemonId == 676) { return R.drawable.p676a; }
        if (pokemonId == 677) { return R.drawable.p677a; }
        if (pokemonId == 678) { return R.drawable.p678a; }
        if (pokemonId == 678) { return R.drawable.p678a; }
        if (pokemonId == 679) { return R.drawable.p679a; }
        if (pokemonId == 680) { return R.drawable.p680a; }
        if (pokemonId == 681) { return R.drawable.p681a; }
        if (pokemonId == 681) { return R.drawable.p681a; }
        if (pokemonId == 682) { return R.drawable.p682a; }
        if (pokemonId == 683) { return R.drawable.p683a; }
        if (pokemonId == 684) { return R.drawable.p684a; }
        if (pokemonId == 685) { return R.drawable.p685a; }
        if (pokemonId == 686) { return R.drawable.p686a; }
        if (pokemonId == 687) { return R.drawable.p687a; }
        if (pokemonId == 688) { return R.drawable.p688a; }
        if (pokemonId == 689) { return R.drawable.p689a; }
        if (pokemonId == 690) { return R.drawable.p690a; }
        if (pokemonId == 691) { return R.drawable.p691a; }
        if (pokemonId == 692) { return R.drawable.p692a; }
        if (pokemonId == 693) { return R.drawable.p693a; }
        if (pokemonId == 694) { return R.drawable.p694a; }
        if (pokemonId == 695) { return R.drawable.p695a; }
        if (pokemonId == 696) { return R.drawable.p696a; }
        if (pokemonId == 697) { return R.drawable.p697a; }
        if (pokemonId == 698) { return R.drawable.p698a; }
        if (pokemonId == 699) { return R.drawable.p699a; }
        if (pokemonId == 700) { return R.drawable.p700a; }
        if (pokemonId == 701) { return R.drawable.p701a; }
        if (pokemonId == 702) { return R.drawable.p702a; }
        if (pokemonId == 703) { return R.drawable.p703a; }
        if (pokemonId == 704) { return R.drawable.p704a; }
        if (pokemonId == 705) { return R.drawable.p705a; }
        if (pokemonId == 706) { return R.drawable.p706a; }
        if (pokemonId == 707) { return R.drawable.p707a; }
        if (pokemonId == 708) { return R.drawable.p708a; }
        if (pokemonId == 709) { return R.drawable.p709a; }
        if (pokemonId == 710) { return R.drawable.p710a; }
        if (pokemonId == 710) { return R.drawable.p710a; }
        if (pokemonId == 710) { return R.drawable.p710a; }
        if (pokemonId == 710) { return R.drawable.p710a; }
        if (pokemonId == 711) { return R.drawable.p711a; }
        if (pokemonId == 711) { return R.drawable.p711a; }
        if (pokemonId == 711) { return R.drawable.p711a; }
        if (pokemonId == 711) { return R.drawable.p711a; }
        if (pokemonId == 712) { return R.drawable.p712a; }
        if (pokemonId == 713) { return R.drawable.p713a; }
        if (pokemonId == 714) { return R.drawable.p714a; }
        if (pokemonId == 715) { return R.drawable.p715a; }
        if (pokemonId == 716) { return R.drawable.p716a; }
        if (pokemonId == 717) { return R.drawable.p717a; }
        if (pokemonId == 718) { return R.drawable.p718a; }
        if (pokemonId == 719) { return R.drawable.p719a; }
        if (pokemonId == 719) { return R.drawable.p719a; }
        if (pokemonId == 720) { return R.drawable.p720confineda; }
        if (pokemonId == 720) { return R.drawable.p720unbounda; }
        if (pokemonId == 721) { return R.drawable.p721a; }
        else { return R.drawable.p0; }
    }
    public static int getShinySprite(int pokemonId, String rawName) {
        if (pokemonId == 1) { return R.drawable.p1a; }
        if (pokemonId == 2) { return R.drawable.p2a; }
        if (pokemonId == 3) { return R.drawable.p3a; }
        if (pokemonId == 3) { return R.drawable.p3a; }
        if (pokemonId == 4) { return R.drawable.p4a; }
        if (pokemonId == 5) { return R.drawable.p5a; }
        if (pokemonId == 6) { return R.drawable.p6a; }
        if (pokemonId == 6) { return R.drawable.p6a; }
        if (pokemonId == 6) { return R.drawable.p6a; }
        if (pokemonId == 7) { return R.drawable.p7a; }
        if (pokemonId == 8) { return R.drawable.p8a; }
        if (pokemonId == 9) { return R.drawable.p9a; }
        if (pokemonId == 9) { return R.drawable.p9a; }
        if (pokemonId == 10) { return R.drawable.p10; }
        if (pokemonId == 11) { return R.drawable.p11; }
        if (pokemonId == 12) { return R.drawable.p12; }
        if (pokemonId == 13) { return R.drawable.p13; }
        if (pokemonId == 14) { return R.drawable.p14; }
        if (pokemonId == 15) { return R.drawable.p15; }
        if (pokemonId == 15) { return R.drawable.p15; }
        if (pokemonId == 16) { return R.drawable.p16; }
        if (pokemonId == 17) { return R.drawable.p17; }
        if (pokemonId == 18) { return R.drawable.p18; }
        if (pokemonId == 18) { return R.drawable.p18; }
        if (pokemonId == 19) { return R.drawable.p19; }
        if (pokemonId == 20) { return R.drawable.p20; }
        if (pokemonId == 21) { return R.drawable.p21; }
        if (pokemonId == 22) { return R.drawable.p22; }
        if (pokemonId == 23) { return R.drawable.p23; }
        if (pokemonId == 24) { return R.drawable.p24; }
        if (pokemonId == 25) { return R.drawable.p25; }
        if (pokemonId == 25) { return R.drawable.p25; }
        if (pokemonId == 25) { return R.drawable.p25; }
        if (pokemonId == 25) { return R.drawable.p25; }
        if (pokemonId == 25) { return R.drawable.p25; }
        if (pokemonId == 25) { return R.drawable.p25; }
        if (pokemonId == 25) { return R.drawable.p25; }
        if (pokemonId == 26) { return R.drawable.p26; }
        if (pokemonId == 27) { return R.drawable.p27; }
        if (pokemonId == 28) { return R.drawable.p28; }
        if (pokemonId == 29) { return R.drawable.p29; }
        if (pokemonId == 30) { return R.drawable.p30; }
        if (pokemonId == 31) { return R.drawable.p31; }
        if (pokemonId == 32) { return R.drawable.p32; }
        if (pokemonId == 33) { return R.drawable.p33; }
        if (pokemonId == 34) { return R.drawable.p34; }
        if (pokemonId == 35) { return R.drawable.p35; }
        if (pokemonId == 36) { return R.drawable.p36; }
        if (pokemonId == 37) { return R.drawable.p37; }
        if (pokemonId == 38) { return R.drawable.p38; }
        if (pokemonId == 39) { return R.drawable.p39; }
        if (pokemonId == 40) { return R.drawable.p40; }
        if (pokemonId == 41) { return R.drawable.p41; }
        if (pokemonId == 42) { return R.drawable.p42; }
        if (pokemonId == 43) { return R.drawable.p43; }
        if (pokemonId == 44) { return R.drawable.p44; }
        if (pokemonId == 45) { return R.drawable.p45; }
        if (pokemonId == 46) { return R.drawable.p46; }
        if (pokemonId == 47) { return R.drawable.p47; }
        if (pokemonId == 48) { return R.drawable.p48; }
        if (pokemonId == 49) { return R.drawable.p49; }
        if (pokemonId == 50) { return R.drawable.p50; }
        if (pokemonId == 51) { return R.drawable.p51; }
        if (pokemonId == 52) { return R.drawable.p52; }
        if (pokemonId == 53) { return R.drawable.p53; }
        if (pokemonId == 54) { return R.drawable.p54; }
        if (pokemonId == 55) { return R.drawable.p55; }
        if (pokemonId == 56) { return R.drawable.p56; }
        if (pokemonId == 57) { return R.drawable.p57; }
        if (pokemonId == 58) { return R.drawable.p58; }
        if (pokemonId == 59) { return R.drawable.p59; }
        if (pokemonId == 60) { return R.drawable.p60; }
        if (pokemonId == 61) { return R.drawable.p61; }
        if (pokemonId == 62) { return R.drawable.p62; }
        if (pokemonId == 63) { return R.drawable.p63; }
        if (pokemonId == 64) { return R.drawable.p64; }
        if (pokemonId == 65) { return R.drawable.p65; }
        if (pokemonId == 65) { return R.drawable.p65; }
        if (pokemonId == 66) { return R.drawable.p66; }
        if (pokemonId == 67) { return R.drawable.p67; }
        if (pokemonId == 68) { return R.drawable.p68; }
        if (pokemonId == 69) { return R.drawable.p69; }
        if (pokemonId == 70) { return R.drawable.p70; }
        if (pokemonId == 71) { return R.drawable.p71; }
        if (pokemonId == 72) { return R.drawable.p72; }
        if (pokemonId == 73) { return R.drawable.p73; }
        if (pokemonId == 74) { return R.drawable.p74; }
        if (pokemonId == 75) { return R.drawable.p75; }
        if (pokemonId == 76) { return R.drawable.p76; }
        if (pokemonId == 77) { return R.drawable.p77; }
        if (pokemonId == 78) { return R.drawable.p78; }
        if (pokemonId == 79) { return R.drawable.p79; }
        if (pokemonId == 80) { return R.drawable.p80; }
        if (pokemonId == 80) { return R.drawable.p80; }
        if (pokemonId == 81) { return R.drawable.p81; }
        if (pokemonId == 82) { return R.drawable.p82; }
        if (pokemonId == 83) { return R.drawable.p83; }
        if (pokemonId == 84) { return R.drawable.p84; }
        if (pokemonId == 85) { return R.drawable.p85; }
        if (pokemonId == 86) { return R.drawable.p86; }
        if (pokemonId == 87) { return R.drawable.p87; }
        if (pokemonId == 88) { return R.drawable.p88; }
        if (pokemonId == 89) { return R.drawable.p89; }
        if (pokemonId == 90) { return R.drawable.p90; }
        if (pokemonId == 91) { return R.drawable.p91; }
        if (pokemonId == 92) { return R.drawable.p92; }
        if (pokemonId == 93) { return R.drawable.p93; }
        if (pokemonId == 94) { return R.drawable.p94; }
        if (pokemonId == 94) { return R.drawable.p94; }
        if (pokemonId == 95) { return R.drawable.p95; }
        if (pokemonId == 96) { return R.drawable.p96; }
        if (pokemonId == 97) { return R.drawable.p97; }
        if (pokemonId == 98) { return R.drawable.p98; }
        if (pokemonId == 99) { return R.drawable.p99; }
        if (pokemonId == 100) { return R.drawable.p100; }
        if (pokemonId == 101) { return R.drawable.p101; }
        if (pokemonId == 102) { return R.drawable.p102; }
        if (pokemonId == 103) { return R.drawable.p103; }
        if (pokemonId == 104) { return R.drawable.p104; }
        if (pokemonId == 105) { return R.drawable.p105; }
        if (pokemonId == 106) { return R.drawable.p106; }
        if (pokemonId == 107) { return R.drawable.p107; }
        if (pokemonId == 108) { return R.drawable.p108; }
        if (pokemonId == 109) { return R.drawable.p109; }
        if (pokemonId == 110) { return R.drawable.p110; }
        if (pokemonId == 111) { return R.drawable.p111; }
        if (pokemonId == 112) { return R.drawable.p112; }
        if (pokemonId == 113) { return R.drawable.p113; }
        if (pokemonId == 114) { return R.drawable.p114; }
        if (pokemonId == 115) { return R.drawable.p115; }
        if (pokemonId == 115) { return R.drawable.p115; }
        if (pokemonId == 116) { return R.drawable.p116; }
        if (pokemonId == 117) { return R.drawable.p117; }
        if (pokemonId == 118) { return R.drawable.p118; }
        if (pokemonId == 119) { return R.drawable.p119; }
        if (pokemonId == 120) { return R.drawable.p120; }
        if (pokemonId == 121) { return R.drawable.p121; }
        if (pokemonId == 122) { return R.drawable.p122; }
        if (pokemonId == 123) { return R.drawable.p123; }
        if (pokemonId == 124) { return R.drawable.p124; }
        if (pokemonId == 125) { return R.drawable.p125; }
        if (pokemonId == 126) { return R.drawable.p126; }
        if (pokemonId == 127) { return R.drawable.p127; }
        if (pokemonId == 127) { return R.drawable.p127; }
        if (pokemonId == 128) { return R.drawable.p128; }
        if (pokemonId == 129) { return R.drawable.p129; }
        if (pokemonId == 130) { return R.drawable.p130; }
        if (pokemonId == 130) { return R.drawable.p130; }
        if (pokemonId == 131) { return R.drawable.p131; }
        if (pokemonId == 132) { return R.drawable.p132; }
        if (pokemonId == 133) { return R.drawable.p133; }
        if (pokemonId == 134) { return R.drawable.p134; }
        if (pokemonId == 135) { return R.drawable.p135; }
        if (pokemonId == 136) { return R.drawable.p136; }
        if (pokemonId == 137) { return R.drawable.p137; }
        if (pokemonId == 138) { return R.drawable.p138; }
        if (pokemonId == 139) { return R.drawable.p139; }
        if (pokemonId == 140) { return R.drawable.p140; }
        if (pokemonId == 141) { return R.drawable.p141; }
        if (pokemonId == 142) { return R.drawable.p142; }
        if (pokemonId == 142) { return R.drawable.p142; }
        if (pokemonId == 143) { return R.drawable.p143; }
        if (pokemonId == 144) { return R.drawable.p144; }
        if (pokemonId == 145) { return R.drawable.p145; }
        if (pokemonId == 146) { return R.drawable.p146; }
        if (pokemonId == 147) { return R.drawable.p147; }
        if (pokemonId == 148) { return R.drawable.p148; }
        if (pokemonId == 149) { return R.drawable.p149; }
        if (pokemonId == 150) { return R.drawable.p150; }
        if (pokemonId == 150) { return R.drawable.p150; }
        if (pokemonId == 150) { return R.drawable.p150; }
        if (pokemonId == 151) { return R.drawable.p151; }
        if (pokemonId == 152) { return R.drawable.p152; }
        if (pokemonId == 153) { return R.drawable.p153; }
        if (pokemonId == 154) { return R.drawable.p154; }
        if (pokemonId == 155) { return R.drawable.p155; }
        if (pokemonId == 156) { return R.drawable.p156; }
        if (pokemonId == 157) { return R.drawable.p157; }
        if (pokemonId == 158) { return R.drawable.p158; }
        if (pokemonId == 159) { return R.drawable.p159; }
        if (pokemonId == 160) { return R.drawable.p160; }
        if (pokemonId == 161) { return R.drawable.p161; }
        if (pokemonId == 162) { return R.drawable.p162; }
        if (pokemonId == 163) { return R.drawable.p163; }
        if (pokemonId == 164) { return R.drawable.p164; }
        if (pokemonId == 165) { return R.drawable.p165; }
        if (pokemonId == 166) { return R.drawable.p166; }
        if (pokemonId == 167) { return R.drawable.p167; }
        if (pokemonId == 168) { return R.drawable.p168; }
        if (pokemonId == 169) { return R.drawable.p169; }
        if (pokemonId == 170) { return R.drawable.p170; }
        if (pokemonId == 171) { return R.drawable.p171; }
        if (pokemonId == 172) { return R.drawable.p172; }
        if (pokemonId == 173) { return R.drawable.p173; }
        if (pokemonId == 174) { return R.drawable.p174; }
        if (pokemonId == 175) { return R.drawable.p175; }
        if (pokemonId == 176) { return R.drawable.p176; }
        if (pokemonId == 177) { return R.drawable.p177; }
        if (pokemonId == 178) { return R.drawable.p178; }
        if (pokemonId == 179) { return R.drawable.p179; }
        if (pokemonId == 180) { return R.drawable.p180; }
        if (pokemonId == 181) { return R.drawable.p181; }
        if (pokemonId == 181) { return R.drawable.p181; }
        if (pokemonId == 182) { return R.drawable.p182; }
        if (pokemonId == 183) { return R.drawable.p183; }
        if (pokemonId == 184) { return R.drawable.p184; }
        if (pokemonId == 185) { return R.drawable.p185; }
        if (pokemonId == 186) { return R.drawable.p186; }
        if (pokemonId == 187) { return R.drawable.p187; }
        if (pokemonId == 188) { return R.drawable.p188; }
        if (pokemonId == 189) { return R.drawable.p189; }
        if (pokemonId == 190) { return R.drawable.p190; }
        if (pokemonId == 191) { return R.drawable.p191; }
        if (pokemonId == 192) { return R.drawable.p192; }
        if (pokemonId == 193) { return R.drawable.p193; }
        if (pokemonId == 194) { return R.drawable.p194; }
        if (pokemonId == 195) { return R.drawable.p195; }
        if (pokemonId == 196) { return R.drawable.p196; }
        if (pokemonId == 197) { return R.drawable.p197; }
        if (pokemonId == 198) { return R.drawable.p198; }
        if (pokemonId == 199) { return R.drawable.p199; }
        if (pokemonId == 200) { return R.drawable.p200; }
        if (pokemonId == 201) { return R.drawable.p201; }
        if (pokemonId == 202) { return R.drawable.p202; }
        if (pokemonId == 203) { return R.drawable.p203; }
        if (pokemonId == 204) { return R.drawable.p204; }
        if (pokemonId == 205) { return R.drawable.p205; }
        if (pokemonId == 206) { return R.drawable.p206; }
        if (pokemonId == 207) { return R.drawable.p207; }
        if (pokemonId == 208) { return R.drawable.p208; }
        if (pokemonId == 208) { return R.drawable.p208; }
        if (pokemonId == 209) { return R.drawable.p209; }
        if (pokemonId == 210) { return R.drawable.p210; }
        if (pokemonId == 211) { return R.drawable.p211; }
        if (pokemonId == 212) { return R.drawable.p212; }
        if (pokemonId == 212) { return R.drawable.p212; }
        if (pokemonId == 213) { return R.drawable.p213; }
        if (pokemonId == 214) { return R.drawable.p214; }
        if (pokemonId == 214) { return R.drawable.p214; }
        if (pokemonId == 215) { return R.drawable.p215; }
        if (pokemonId == 216) { return R.drawable.p216; }
        if (pokemonId == 217) { return R.drawable.p217; }
        if (pokemonId == 218) { return R.drawable.p218; }
        if (pokemonId == 219) { return R.drawable.p219; }
        if (pokemonId == 220) { return R.drawable.p220; }
        if (pokemonId == 221) { return R.drawable.p221; }
        if (pokemonId == 222) { return R.drawable.p222; }
        if (pokemonId == 223) { return R.drawable.p223; }
        if (pokemonId == 224) { return R.drawable.p224; }
        if (pokemonId == 225) { return R.drawable.p225; }
        if (pokemonId == 226) { return R.drawable.p226; }
        if (pokemonId == 227) { return R.drawable.p227; }
        if (pokemonId == 228) { return R.drawable.p228; }
        if (pokemonId == 229) { return R.drawable.p229; }
        if (pokemonId == 229) { return R.drawable.p229; }
        if (pokemonId == 230) { return R.drawable.p230; }
        if (pokemonId == 231) { return R.drawable.p231; }
        if (pokemonId == 232) { return R.drawable.p232; }
        if (pokemonId == 233) { return R.drawable.p233; }
        if (pokemonId == 234) { return R.drawable.p234; }
        if (pokemonId == 235) { return R.drawable.p235; }
        if (pokemonId == 236) { return R.drawable.p236; }
        if (pokemonId == 237) { return R.drawable.p237; }
        if (pokemonId == 238) { return R.drawable.p238; }
        if (pokemonId == 239) { return R.drawable.p239; }
        if (pokemonId == 240) { return R.drawable.p240; }
        if (pokemonId == 241) { return R.drawable.p241; }
        if (pokemonId == 242) { return R.drawable.p242; }
        if (pokemonId == 243) { return R.drawable.p243; }
        if (pokemonId == 244) { return R.drawable.p244; }
        if (pokemonId == 245) { return R.drawable.p245; }
        if (pokemonId == 246) { return R.drawable.p246; }
        if (pokemonId == 247) { return R.drawable.p247; }
        if (pokemonId == 248) { return R.drawable.p248; }
        if (pokemonId == 248) { return R.drawable.p248; }
        if (pokemonId == 249) { return R.drawable.p249; }
        if (pokemonId == 250) { return R.drawable.p250; }
        if (pokemonId == 251) { return R.drawable.p251; }
        if (pokemonId == 252) { return R.drawable.p252; }
        if (pokemonId == 253) { return R.drawable.p253; }
        if (pokemonId == 254) { return R.drawable.p254; }
        if (pokemonId == 254) { return R.drawable.p254; }
        if (pokemonId == 255) { return R.drawable.p255; }
        if (pokemonId == 256) { return R.drawable.p256; }
        if (pokemonId == 257) { return R.drawable.p257; }
        if (pokemonId == 257) { return R.drawable.p257; }
        if (pokemonId == 258) { return R.drawable.p258; }
        if (pokemonId == 259) { return R.drawable.p259; }
        if (pokemonId == 260) { return R.drawable.p260; }
        if (pokemonId == 260) { return R.drawable.p260; }
        if (pokemonId == 261) { return R.drawable.p261; }
        if (pokemonId == 262) { return R.drawable.p262; }
        if (pokemonId == 263) { return R.drawable.p263; }
        if (pokemonId == 264) { return R.drawable.p264; }
        if (pokemonId == 265) { return R.drawable.p265; }
        if (pokemonId == 266) { return R.drawable.p266; }
        if (pokemonId == 267) { return R.drawable.p267; }
        if (pokemonId == 268) { return R.drawable.p268; }
        if (pokemonId == 269) { return R.drawable.p269; }
        if (pokemonId == 270) { return R.drawable.p270; }
        if (pokemonId == 271) { return R.drawable.p271; }
        if (pokemonId == 272) { return R.drawable.p272; }
        if (pokemonId == 273) { return R.drawable.p273; }
        if (pokemonId == 274) { return R.drawable.p274; }
        if (pokemonId == 275) { return R.drawable.p275; }
        if (pokemonId == 276) { return R.drawable.p276; }
        if (pokemonId == 277) { return R.drawable.p277; }
        if (pokemonId == 278) { return R.drawable.p278; }
        if (pokemonId == 279) { return R.drawable.p279; }
        if (pokemonId == 280) { return R.drawable.p280; }
        if (pokemonId == 281) { return R.drawable.p281; }
        if (pokemonId == 282) { return R.drawable.p282; }
        if (pokemonId == 282) { return R.drawable.p282; }
        if (pokemonId == 283) { return R.drawable.p283; }
        if (pokemonId == 284) { return R.drawable.p284; }
        if (pokemonId == 285) { return R.drawable.p285; }
        if (pokemonId == 286) { return R.drawable.p286; }
        if (pokemonId == 287) { return R.drawable.p287; }
        if (pokemonId == 288) { return R.drawable.p288; }
        if (pokemonId == 289) { return R.drawable.p289; }
        if (pokemonId == 290) { return R.drawable.p290; }
        if (pokemonId == 291) { return R.drawable.p291; }
        if (pokemonId == 292) { return R.drawable.p292; }
        if (pokemonId == 293) { return R.drawable.p293; }
        if (pokemonId == 294) { return R.drawable.p294; }
        if (pokemonId == 295) { return R.drawable.p295; }
        if (pokemonId == 296) { return R.drawable.p296; }
        if (pokemonId == 297) { return R.drawable.p297; }
        if (pokemonId == 298) { return R.drawable.p298; }
        if (pokemonId == 299) { return R.drawable.p299; }
        if (pokemonId == 300) { return R.drawable.p300; }
        if (pokemonId == 301) { return R.drawable.p301; }
        if (pokemonId == 302) { return R.drawable.p302; }
        if (pokemonId == 302) { return R.drawable.p302; }
        if (pokemonId == 303) { return R.drawable.p303; }
        if (pokemonId == 303) { return R.drawable.p303; }
        if (pokemonId == 304) { return R.drawable.p304; }
        if (pokemonId == 305) { return R.drawable.p305; }
        if (pokemonId == 306) { return R.drawable.p306; }
        if (pokemonId == 306) { return R.drawable.p306; }
        if (pokemonId == 307) { return R.drawable.p307; }
        if (pokemonId == 308) { return R.drawable.p308; }
        if (pokemonId == 308) { return R.drawable.p308; }
        if (pokemonId == 309) { return R.drawable.p309; }
        if (pokemonId == 310) { return R.drawable.p310; }
        if (pokemonId == 310) { return R.drawable.p310; }
        if (pokemonId == 311) { return R.drawable.p311; }
        if (pokemonId == 312) { return R.drawable.p312; }
        if (pokemonId == 313) { return R.drawable.p313; }
        if (pokemonId == 314) { return R.drawable.p314; }
        if (pokemonId == 315) { return R.drawable.p315; }
        if (pokemonId == 316) { return R.drawable.p316; }
        if (pokemonId == 317) { return R.drawable.p317; }
        if (pokemonId == 318) { return R.drawable.p318; }
        if (pokemonId == 319) { return R.drawable.p319; }
        if (pokemonId == 319) { return R.drawable.p319; }
        if (pokemonId == 320) { return R.drawable.p320; }
        if (pokemonId == 321) { return R.drawable.p321; }
        if (pokemonId == 322) { return R.drawable.p322; }
        if (pokemonId == 323) { return R.drawable.p323; }
        if (pokemonId == 323) { return R.drawable.p323; }
        if (pokemonId == 324) { return R.drawable.p324; }
        if (pokemonId == 325) { return R.drawable.p325; }
        if (pokemonId == 326) { return R.drawable.p326; }
        if (pokemonId == 327) { return R.drawable.p327; }
        if (pokemonId == 328) { return R.drawable.p328; }
        if (pokemonId == 329) { return R.drawable.p329; }
        if (pokemonId == 330) { return R.drawable.p330; }
        if (pokemonId == 331) { return R.drawable.p331; }
        if (pokemonId == 332) { return R.drawable.p332; }
        if (pokemonId == 333) { return R.drawable.p333; }
        if (pokemonId == 334) { return R.drawable.p334; }
        if (pokemonId == 334) { return R.drawable.p334; }
        if (pokemonId == 335) { return R.drawable.p335; }
        if (pokemonId == 336) { return R.drawable.p336; }
        if (pokemonId == 337) { return R.drawable.p337; }
        if (pokemonId == 338) { return R.drawable.p338; }
        if (pokemonId == 339) { return R.drawable.p339; }
        if (pokemonId == 340) { return R.drawable.p340; }
        if (pokemonId == 341) { return R.drawable.p341; }
        if (pokemonId == 342) { return R.drawable.p342; }
        if (pokemonId == 343) { return R.drawable.p343; }
        if (pokemonId == 344) { return R.drawable.p344; }
        if (pokemonId == 345) { return R.drawable.p345; }
        if (pokemonId == 346) { return R.drawable.p346; }
        if (pokemonId == 347) { return R.drawable.p347; }
        if (pokemonId == 348) { return R.drawable.p348; }
        if (pokemonId == 349) { return R.drawable.p349; }
        if (pokemonId == 350) { return R.drawable.p350; }
        if (pokemonId == 351) { return R.drawable.p351; }
        if (pokemonId == 351) { return R.drawable.p351; }
        if (pokemonId == 351) { return R.drawable.p351; }
        if (pokemonId == 351) { return R.drawable.p351; }
        if (pokemonId == 352) { return R.drawable.p352; }
        if (pokemonId == 353) { return R.drawable.p353; }
        if (pokemonId == 354) { return R.drawable.p354; }
        if (pokemonId == 354) { return R.drawable.p354; }
        if (pokemonId == 355) { return R.drawable.p355; }
        if (pokemonId == 356) { return R.drawable.p356; }
        if (pokemonId == 357) { return R.drawable.p357; }
        if (pokemonId == 358) { return R.drawable.p358; }
        if (pokemonId == 359) { return R.drawable.p359; }
        if (pokemonId == 359) { return R.drawable.p359; }
        if (pokemonId == 360) { return R.drawable.p360; }
        if (pokemonId == 361) { return R.drawable.p361; }
        if (pokemonId == 362) { return R.drawable.p362; }
        if (pokemonId == 362) { return R.drawable.p362; }
        if (pokemonId == 363) { return R.drawable.p363; }
        if (pokemonId == 364) { return R.drawable.p364; }
        if (pokemonId == 365) { return R.drawable.p365; }
        if (pokemonId == 366) { return R.drawable.p366; }
        if (pokemonId == 367) { return R.drawable.p367; }
        if (pokemonId == 368) { return R.drawable.p368; }
        if (pokemonId == 369) { return R.drawable.p369; }
        if (pokemonId == 370) { return R.drawable.p370; }
        if (pokemonId == 371) { return R.drawable.p371; }
        if (pokemonId == 372) { return R.drawable.p372; }
        if (pokemonId == 373) { return R.drawable.p373; }
        if (pokemonId == 373) { return R.drawable.p373; }
        if (pokemonId == 374) { return R.drawable.p374; }
        if (pokemonId == 375) { return R.drawable.p375; }
        if (pokemonId == 376) { return R.drawable.p376; }
        if (pokemonId == 376) { return R.drawable.p376; }
        if (pokemonId == 377) { return R.drawable.p377; }
        if (pokemonId == 378) { return R.drawable.p378; }
        if (pokemonId == 379) { return R.drawable.p379; }
        if (pokemonId == 380) { return R.drawable.p380; }
        if (pokemonId == 380) { return R.drawable.p380; }
        if (pokemonId == 381) { return R.drawable.p381; }
        if (pokemonId == 381) { return R.drawable.p381; }
        if (pokemonId == 382) { return R.drawable.p382; }
        if (pokemonId == 382) { return R.drawable.p382; }
        if (pokemonId == 383) { return R.drawable.p383; }
        if (pokemonId == 383) { return R.drawable.p383; }
        if (pokemonId == 384) { return R.drawable.p384; }
        if (pokemonId == 384) { return R.drawable.p384; }
        if (pokemonId == 385) { return R.drawable.p385; }
        if (pokemonId == 386) { return R.drawable.p386; }
        if (pokemonId == 386) { return R.drawable.p386; }
        if (pokemonId == 386) { return R.drawable.p386; }
        if (pokemonId == 386) { return R.drawable.p386; }
        if (pokemonId == 387) { return R.drawable.p387; }
        if (pokemonId == 388) { return R.drawable.p388; }
        if (pokemonId == 389) { return R.drawable.p389; }
        if (pokemonId == 390) { return R.drawable.p390; }
        if (pokemonId == 391) { return R.drawable.p391; }
        if (pokemonId == 392) { return R.drawable.p392; }
        if (pokemonId == 393) { return R.drawable.p393; }
        if (pokemonId == 394) { return R.drawable.p394; }
        if (pokemonId == 395) { return R.drawable.p395; }
        if (pokemonId == 396) { return R.drawable.p396; }
        if (pokemonId == 397) { return R.drawable.p397; }
        if (pokemonId == 398) { return R.drawable.p398; }
        if (pokemonId == 399) { return R.drawable.p399; }
        if (pokemonId == 400) { return R.drawable.p400; }
        if (pokemonId == 401) { return R.drawable.p401; }
        if (pokemonId == 402) { return R.drawable.p402; }
        if (pokemonId == 403) { return R.drawable.p403; }
        if (pokemonId == 404) { return R.drawable.p404; }
        if (pokemonId == 405) { return R.drawable.p405; }
        if (pokemonId == 406) { return R.drawable.p406; }
        if (pokemonId == 407) { return R.drawable.p407; }
        if (pokemonId == 408) { return R.drawable.p408; }
        if (pokemonId == 409) { return R.drawable.p409; }
        if (pokemonId == 410) { return R.drawable.p410; }
        if (pokemonId == 411) { return R.drawable.p411; }
        if (pokemonId == 412) { return R.drawable.p412; }
        if (pokemonId == 413) { return R.drawable.p413; }
        if (pokemonId == 413) { return R.drawable.p413; }
        if (pokemonId == 413) { return R.drawable.p413; }
        if (pokemonId == 414) { return R.drawable.p414; }
        if (pokemonId == 415) { return R.drawable.p415; }
        if (pokemonId == 416) { return R.drawable.p416; }
        if (pokemonId == 417) { return R.drawable.p417; }
        if (pokemonId == 418) { return R.drawable.p418; }
        if (pokemonId == 419) { return R.drawable.p419; }
        if (pokemonId == 420) { return R.drawable.p420; }
        if (pokemonId == 421) { return R.drawable.p421; }
        if (pokemonId == 422) { return R.drawable.p422; }
        if (pokemonId == 423) { return R.drawable.p423; }
        if (pokemonId == 424) { return R.drawable.p424; }
        if (pokemonId == 425) { return R.drawable.p425; }
        if (pokemonId == 426) { return R.drawable.p426; }
        if (pokemonId == 427) { return R.drawable.p427; }
        if (pokemonId == 428) { return R.drawable.p428; }
        if (pokemonId == 428) { return R.drawable.p428; }
        if (pokemonId == 429) { return R.drawable.p429; }
        if (pokemonId == 430) { return R.drawable.p430; }
        if (pokemonId == 431) { return R.drawable.p431; }
        if (pokemonId == 432) { return R.drawable.p432; }
        if (pokemonId == 433) { return R.drawable.p433; }
        if (pokemonId == 434) { return R.drawable.p434; }
        if (pokemonId == 435) { return R.drawable.p435; }
        if (pokemonId == 436) { return R.drawable.p436; }
        if (pokemonId == 437) { return R.drawable.p437; }
        if (pokemonId == 438) { return R.drawable.p438; }
        if (pokemonId == 439) { return R.drawable.p439; }
        if (pokemonId == 440) { return R.drawable.p440; }
        if (pokemonId == 441) { return R.drawable.p441; }
        if (pokemonId == 442) { return R.drawable.p442; }
        if (pokemonId == 443) { return R.drawable.p443; }
        if (pokemonId == 444) { return R.drawable.p444; }
        if (pokemonId == 445) { return R.drawable.p445; }
        if (pokemonId == 445) { return R.drawable.p445; }
        if (pokemonId == 446) { return R.drawable.p446; }
        if (pokemonId == 447) { return R.drawable.p447; }
        if (pokemonId == 448) { return R.drawable.p448; }
        if (pokemonId == 448) { return R.drawable.p448; }
        if (pokemonId == 449) { return R.drawable.p449; }
        if (pokemonId == 450) { return R.drawable.p450; }
        if (pokemonId == 451) { return R.drawable.p451; }
        if (pokemonId == 452) { return R.drawable.p452; }
        if (pokemonId == 453) { return R.drawable.p453; }
        if (pokemonId == 454) { return R.drawable.p454; }
        if (pokemonId == 455) { return R.drawable.p455; }
        if (pokemonId == 456) { return R.drawable.p456; }
        if (pokemonId == 457) { return R.drawable.p457; }
        if (pokemonId == 458) { return R.drawable.p458; }
        if (pokemonId == 459) { return R.drawable.p459; }
        if (pokemonId == 460) { return R.drawable.p460; }
        if (pokemonId == 460) { return R.drawable.p460; }
        if (pokemonId == 461) { return R.drawable.p461; }
        if (pokemonId == 462) { return R.drawable.p462; }
        if (pokemonId == 463) { return R.drawable.p463; }
        if (pokemonId == 464) { return R.drawable.p464; }
        if (pokemonId == 465) { return R.drawable.p465; }
        if (pokemonId == 466) { return R.drawable.p466; }
        if (pokemonId == 467) { return R.drawable.p467; }
        if (pokemonId == 468) { return R.drawable.p468; }
        if (pokemonId == 469) { return R.drawable.p469; }
        if (pokemonId == 470) { return R.drawable.p470; }
        if (pokemonId == 471) { return R.drawable.p471; }
        if (pokemonId == 472) { return R.drawable.p472; }
        if (pokemonId == 473) { return R.drawable.p473; }
        if (pokemonId == 474) { return R.drawable.p474; }
        if (pokemonId == 475) { return R.drawable.p475; }
        if (pokemonId == 475) { return R.drawable.p475; }
        if (pokemonId == 476) { return R.drawable.p476; }
        if (pokemonId == 477) { return R.drawable.p477; }
        if (pokemonId == 478) { return R.drawable.p478; }
        if (pokemonId == 479) { return R.drawable.p479; }
        if (pokemonId == 479) { return R.drawable.p479; }
        if (pokemonId == 479) { return R.drawable.p479; }
        if (pokemonId == 479) { return R.drawable.p479; }
        if (pokemonId == 479) { return R.drawable.p479; }
        if (pokemonId == 479) { return R.drawable.p479; }
        if (pokemonId == 480) { return R.drawable.p480; }
        if (pokemonId == 481) { return R.drawable.p481; }
        if (pokemonId == 482) { return R.drawable.p482; }
        if (pokemonId == 483) { return R.drawable.p483; }
        if (pokemonId == 484) { return R.drawable.p484; }
        if (pokemonId == 485) { return R.drawable.p485; }
        if (pokemonId == 486) { return R.drawable.p486; }
        if (pokemonId == 487) { return R.drawable.p487; }
        if (pokemonId == 487) { return R.drawable.p487; }
        if (pokemonId == 488) { return R.drawable.p488; }
        if (pokemonId == 489) { return R.drawable.p489; }
        if (pokemonId == 490) { return R.drawable.p490; }
        if (pokemonId == 491) { return R.drawable.p491; }
        if (pokemonId == 492) { return R.drawable.p492; }
        if (pokemonId == 492) { return R.drawable.p492; }
        if (pokemonId == 493) { return R.drawable.p493; }
        if (pokemonId == 494) { return R.drawable.p494; }
        if (pokemonId == 495) { return R.drawable.p495; }
        if (pokemonId == 496) { return R.drawable.p496; }
        if (pokemonId == 497) { return R.drawable.p497; }
        if (pokemonId == 498) { return R.drawable.p498; }
        if (pokemonId == 499) { return R.drawable.p499; }
        if (pokemonId == 500) { return R.drawable.p500; }
        if (pokemonId == 501) { return R.drawable.p501; }
        if (pokemonId == 502) { return R.drawable.p502; }
        if (pokemonId == 503) { return R.drawable.p503; }
        if (pokemonId == 504) { return R.drawable.p504; }
        if (pokemonId == 505) { return R.drawable.p505; }
        if (pokemonId == 506) { return R.drawable.p506; }
        if (pokemonId == 507) { return R.drawable.p507; }
        if (pokemonId == 508) { return R.drawable.p508; }
        if (pokemonId == 509) { return R.drawable.p509; }
        if (pokemonId == 510) { return R.drawable.p510; }
        if (pokemonId == 511) { return R.drawable.p511; }
        if (pokemonId == 512) { return R.drawable.p512; }
        if (pokemonId == 513) { return R.drawable.p513; }
        if (pokemonId == 514) { return R.drawable.p514; }
        if (pokemonId == 515) { return R.drawable.p515; }
        if (pokemonId == 516) { return R.drawable.p516; }
        if (pokemonId == 517) { return R.drawable.p517; }
        if (pokemonId == 518) { return R.drawable.p518; }
        if (pokemonId == 519) { return R.drawable.p519; }
        if (pokemonId == 520) { return R.drawable.p520; }
        if (pokemonId == 521) { return R.drawable.p521; }
        if (pokemonId == 522) { return R.drawable.p522; }
        if (pokemonId == 523) { return R.drawable.p523; }
        if (pokemonId == 524) { return R.drawable.p524; }
        if (pokemonId == 525) { return R.drawable.p525; }
        if (pokemonId == 526) { return R.drawable.p526; }
        if (pokemonId == 527) { return R.drawable.p527; }
        if (pokemonId == 528) { return R.drawable.p528; }
        if (pokemonId == 529) { return R.drawable.p529; }
        if (pokemonId == 530) { return R.drawable.p530; }
        if (pokemonId == 531) { return R.drawable.p531; }
        if (pokemonId == 531) { return R.drawable.p531; }
        if (pokemonId == 532) { return R.drawable.p532; }
        if (pokemonId == 533) { return R.drawable.p533; }
        if (pokemonId == 534) { return R.drawable.p534; }
        if (pokemonId == 535) { return R.drawable.p535; }
        if (pokemonId == 536) { return R.drawable.p536; }
        if (pokemonId == 537) { return R.drawable.p537; }
        if (pokemonId == 538) { return R.drawable.p538; }
        if (pokemonId == 539) { return R.drawable.p539; }
        if (pokemonId == 540) { return R.drawable.p540; }
        if (pokemonId == 541) { return R.drawable.p541; }
        if (pokemonId == 542) { return R.drawable.p542; }
        if (pokemonId == 543) { return R.drawable.p543; }
        if (pokemonId == 544) { return R.drawable.p544; }
        if (pokemonId == 545) { return R.drawable.p545; }
        if (pokemonId == 546) { return R.drawable.p546; }
        if (pokemonId == 547) { return R.drawable.p547; }
        if (pokemonId == 548) { return R.drawable.p548; }
        if (pokemonId == 549) { return R.drawable.p549; }
        if (pokemonId == 550) { return R.drawable.p550; }
        if (pokemonId == 550) { return R.drawable.p550; }
        if (pokemonId == 551) { return R.drawable.p551; }
        if (pokemonId == 552) { return R.drawable.p552; }
        if (pokemonId == 553) { return R.drawable.p553; }
        if (pokemonId == 554) { return R.drawable.p554; }
        if (pokemonId == 555) { return R.drawable.p555; }
        if (pokemonId == 555) { return R.drawable.p555; }
        if (pokemonId == 556) { return R.drawable.p556; }
        if (pokemonId == 557) { return R.drawable.p557; }
        if (pokemonId == 558) { return R.drawable.p558; }
        if (pokemonId == 559) { return R.drawable.p559; }
        if (pokemonId == 560) { return R.drawable.p560; }
        if (pokemonId == 561) { return R.drawable.p561; }
        if (pokemonId == 562) { return R.drawable.p562; }
        if (pokemonId == 563) { return R.drawable.p563; }
        if (pokemonId == 564) { return R.drawable.p564; }
        if (pokemonId == 565) { return R.drawable.p565; }
        if (pokemonId == 566) { return R.drawable.p566; }
        if (pokemonId == 567) { return R.drawable.p567; }
        if (pokemonId == 568) { return R.drawable.p568; }
        if (pokemonId == 569) { return R.drawable.p569; }
        if (pokemonId == 570) { return R.drawable.p570; }
        if (pokemonId == 571) { return R.drawable.p571; }
        if (pokemonId == 572) { return R.drawable.p572; }
        if (pokemonId == 573) { return R.drawable.p573; }
        if (pokemonId == 574) { return R.drawable.p574; }
        if (pokemonId == 575) { return R.drawable.p575; }
        if (pokemonId == 576) { return R.drawable.p576; }
        if (pokemonId == 577) { return R.drawable.p577; }
        if (pokemonId == 578) { return R.drawable.p578; }
        if (pokemonId == 579) { return R.drawable.p579; }
        if (pokemonId == 580) { return R.drawable.p580; }
        if (pokemonId == 581) { return R.drawable.p581; }
        if (pokemonId == 582) { return R.drawable.p582; }
        if (pokemonId == 583) { return R.drawable.p583; }
        if (pokemonId == 584) { return R.drawable.p584; }
        if (pokemonId == 585) { return R.drawable.p585; }
        if (pokemonId == 586) { return R.drawable.p586; }
        if (pokemonId == 587) { return R.drawable.p587; }
        if (pokemonId == 588) { return R.drawable.p588; }
        if (pokemonId == 589) { return R.drawable.p589; }
        if (pokemonId == 590) { return R.drawable.p590; }
        if (pokemonId == 591) { return R.drawable.p591; }
        if (pokemonId == 592) { return R.drawable.p592; }
        if (pokemonId == 593) { return R.drawable.p593; }
        if (pokemonId == 594) { return R.drawable.p594; }
        if (pokemonId == 595) { return R.drawable.p595; }
        if (pokemonId == 596) { return R.drawable.p596; }
        if (pokemonId == 597) { return R.drawable.p597; }
        if (pokemonId == 598) { return R.drawable.p598; }
        if (pokemonId == 599) { return R.drawable.p599; }
        if (pokemonId == 600) { return R.drawable.p600; }
        if (pokemonId == 601) { return R.drawable.p601; }
        if (pokemonId == 602) { return R.drawable.p602; }
        if (pokemonId == 603) { return R.drawable.p603; }
        if (pokemonId == 604) { return R.drawable.p604; }
        if (pokemonId == 605) { return R.drawable.p605; }
        if (pokemonId == 606) { return R.drawable.p606; }
        if (pokemonId == 607) { return R.drawable.p607; }
        if (pokemonId == 608) { return R.drawable.p608; }
        if (pokemonId == 609) { return R.drawable.p609; }
        if (pokemonId == 610) { return R.drawable.p610; }
        if (pokemonId == 611) { return R.drawable.p611; }
        if (pokemonId == 612) { return R.drawable.p612; }
        if (pokemonId == 613) { return R.drawable.p613; }
        if (pokemonId == 614) { return R.drawable.p614; }
        if (pokemonId == 615) { return R.drawable.p615; }
        if (pokemonId == 616) { return R.drawable.p616; }
        if (pokemonId == 617) { return R.drawable.p617; }
        if (pokemonId == 618) { return R.drawable.p618; }
        if (pokemonId == 619) { return R.drawable.p619; }
        if (pokemonId == 620) { return R.drawable.p620; }
        if (pokemonId == 621) { return R.drawable.p621; }
        if (pokemonId == 622) { return R.drawable.p622; }
        if (pokemonId == 623) { return R.drawable.p623; }
        if (pokemonId == 624) { return R.drawable.p624; }
        if (pokemonId == 625) { return R.drawable.p625; }
        if (pokemonId == 626) { return R.drawable.p626; }
        if (pokemonId == 627) { return R.drawable.p627; }
        if (pokemonId == 628) { return R.drawable.p628; }
        if (pokemonId == 629) { return R.drawable.p629; }
        if (pokemonId == 630) { return R.drawable.p630; }
        if (pokemonId == 631) { return R.drawable.p631; }
        if (pokemonId == 632) { return R.drawable.p632; }
        if (pokemonId == 633) { return R.drawable.p633; }
        if (pokemonId == 634) { return R.drawable.p634; }
        if (pokemonId == 635) { return R.drawable.p635; }
        if (pokemonId == 636) { return R.drawable.p636; }
        if (pokemonId == 637) { return R.drawable.p637; }
        if (pokemonId == 638) { return R.drawable.p638; }
        if (pokemonId == 639) { return R.drawable.p639; }
        if (pokemonId == 640) { return R.drawable.p640; }
        if (pokemonId == 641) { return R.drawable.p641; }
        if (pokemonId == 641) { return R.drawable.p641; }
        if (pokemonId == 642) { return R.drawable.p642; }
        if (pokemonId == 642) { return R.drawable.p642; }
        if (pokemonId == 643) { return R.drawable.p643; }
        if (pokemonId == 644) { return R.drawable.p644; }
        if (pokemonId == 645) { return R.drawable.p645; }
        if (pokemonId == 645) { return R.drawable.p645; }
        if (pokemonId == 646) { return R.drawable.p646; }
        if (pokemonId == 646) { return R.drawable.p646; }
        if (pokemonId == 646) { return R.drawable.p646; }
        if (pokemonId == 647) { return R.drawable.p647resolute_form; }
        if (pokemonId == 647) { return R.drawable.p647standard_form; }
        if (pokemonId == 648) { return R.drawable.p648; }
        if (pokemonId == 648) { return R.drawable.p648; }
        if (pokemonId == 649) { return R.drawable.p649; }
        if (pokemonId == 650) { return R.drawable.p650; }
        if (pokemonId == 651) { return R.drawable.p651; }
        if (pokemonId == 652) { return R.drawable.p652; }
        if (pokemonId == 653) { return R.drawable.p653; }
        if (pokemonId == 654) { return R.drawable.p654; }
        if (pokemonId == 655) { return R.drawable.p655; }
        if (pokemonId == 656) { return R.drawable.p656; }
        if (pokemonId == 657) { return R.drawable.p657; }
        if (pokemonId == 658) { return R.drawable.p658; }
        if (pokemonId == 659) { return R.drawable.p659; }
        if (pokemonId == 660) { return R.drawable.p660; }
        if (pokemonId == 661) { return R.drawable.p661; }
        if (pokemonId == 662) { return R.drawable.p662; }
        if (pokemonId == 663) { return R.drawable.p663; }
        if (pokemonId == 664) { return R.drawable.p664; }
        if (pokemonId == 665) { return R.drawable.p665; }
        if (pokemonId == 666) { return R.drawable.p666; }
        if (pokemonId == 667) { return R.drawable.p667; }
        if (pokemonId == 668) { return R.drawable.p668; }
        if (pokemonId == 669) { return R.drawable.p669; }
        if (pokemonId == 670) { return R.drawable.p670; }
        if (pokemonId == 670) { return R.drawable.p670; }
        if (pokemonId == 671) { return R.drawable.p671; }
        if (pokemonId == 672) { return R.drawable.p672; }
        if (pokemonId == 673) { return R.drawable.p673; }
        if (pokemonId == 674) { return R.drawable.p674; }
        if (pokemonId == 675) { return R.drawable.p675; }
        if (pokemonId == 676) { return R.drawable.p676; }
        if (pokemonId == 677) { return R.drawable.p677; }
        if (pokemonId == 678) { return R.drawable.p678; }
        if (pokemonId == 678) { return R.drawable.p678; }
        if (pokemonId == 679) { return R.drawable.p679; }
        if (pokemonId == 680) { return R.drawable.p680; }
        if (pokemonId == 681) { return R.drawable.p681; }
        if (pokemonId == 681) { return R.drawable.p681; }
        if (pokemonId == 682) { return R.drawable.p682; }
        if (pokemonId == 683) { return R.drawable.p683; }
        if (pokemonId == 684) { return R.drawable.p684; }
        if (pokemonId == 685) { return R.drawable.p685; }
        if (pokemonId == 686) { return R.drawable.p686; }
        if (pokemonId == 687) { return R.drawable.p687; }
        if (pokemonId == 688) { return R.drawable.p688; }
        if (pokemonId == 689) { return R.drawable.p689; }
        if (pokemonId == 690) { return R.drawable.p690; }
        if (pokemonId == 691) { return R.drawable.p691; }
        if (pokemonId == 692) { return R.drawable.p692; }
        if (pokemonId == 693) { return R.drawable.p693; }
        if (pokemonId == 694) { return R.drawable.p694; }
        if (pokemonId == 695) { return R.drawable.p695; }
        if (pokemonId == 696) { return R.drawable.p696; }
        if (pokemonId == 697) { return R.drawable.p697; }
        if (pokemonId == 698) { return R.drawable.p698; }
        if (pokemonId == 699) { return R.drawable.p699; }
        if (pokemonId == 700) { return R.drawable.p700; }
        if (pokemonId == 701) { return R.drawable.p701; }
        if (pokemonId == 702) { return R.drawable.p702; }
        if (pokemonId == 703) { return R.drawable.p703; }
        if (pokemonId == 704) { return R.drawable.p704; }
        if (pokemonId == 705) { return R.drawable.p705; }
        if (pokemonId == 706) { return R.drawable.p706; }
        if (pokemonId == 707) { return R.drawable.p707; }
        if (pokemonId == 708) { return R.drawable.p708; }
        if (pokemonId == 709) { return R.drawable.p709; }
        if (pokemonId == 710) { return R.drawable.p710; }
        if (pokemonId == 710) { return R.drawable.p710; }
        if (pokemonId == 710) { return R.drawable.p710; }
        if (pokemonId == 710) { return R.drawable.p710; }
        if (pokemonId == 711) { return R.drawable.p711; }
        if (pokemonId == 711) { return R.drawable.p711; }
        if (pokemonId == 711) { return R.drawable.p711; }
        if (pokemonId == 711) { return R.drawable.p711; }
        if (pokemonId == 712) { return R.drawable.p712; }
        if (pokemonId == 713) { return R.drawable.p713; }
        if (pokemonId == 714) { return R.drawable.p714; }
        if (pokemonId == 715) { return R.drawable.p715; }
        if (pokemonId == 716) { return R.drawable.p716; }
        if (pokemonId == 717) { return R.drawable.p717; }
        if (pokemonId == 718) { return R.drawable.p718; }
        if (pokemonId == 719) { return R.drawable.p719; }
        if (pokemonId == 719) { return R.drawable.p719; }
        if (pokemonId == 720) { return R.drawable.p720confined; }
        if (pokemonId == 720) { return R.drawable.p720unbound; }
        if (pokemonId == 721) { return R.drawable.p721; }
        else { return R.drawable.p0; }
    }
*/
}
