begin transaction;

update moves set description = 'The target is physically pounded with a long tail, a foreleg, or the like.' where id = 1;
update moves set description = 'The target is attacked with a sharp chop. Critical hits land more easily.' where id = 2;
update moves set description = 'The target is slapped repeatedly, back and forth, two to five times in a row.' where id = 3;
update moves set description = 'The target is hit with a flurry of punches that strike two to five times in a row.' where id = 4;
update moves set description = 'The target is slugged by a punch thrown with muscle-packed power.' where id = 5;
update moves set description = 'Numerous coins are hurled at the target to inflict damage. Money is earned after the battle.' where id = 6;
update moves set description = 'The target is punched with a fiery fist. This may also leave the target with a burn.' where id = 7;
update moves set description = 'The target is punched with an icy fist. This may also leave the target frozen.' where id = 8;
update moves set description = 'The target is punched with an electrified fist. This may also leave the target with paralysis.' where id = 9;
update moves set description = 'Hard, pointed, sharp claws rake the target to inflict damage.' where id = 10;
update moves set description = 'The target is gripped and squeezed from both sides to inflict damage.' where id = 11;
update moves set description = 'A vicious, tearing attack with big pincers. The target faints instantly if this attack hits' where id = 12;
update moves set description = 'A two-turn attack. Blades of wind hit opposing Pokemon on the second turn. Critical hits land more easily.' where id = 13;
update moves set description = 'A frenetic dance to uplift the fighting spirit. This sharply raises the user''s Attack stat.' where id = 14;
update moves set description = 'The target is cut with a scythe or claw. This can also be used to cut down thin trees.' where id = 15;
update moves set description = 'A gust of wind is whipped up by wings and launched at the target to inflict damage.' where id = 16;
update moves set description = 'The target is struck with large, imposing wings spread wide to inflict damage.' where id = 17;
update moves set description = 'The target is blown away, and a different Pokemon is dragged out. In the wild, this ends a battle against a single Pokemon.' where id = 18;
update moves set description = 'The user soars and then strikes its target on the next turn. This can also be used to fly to any familiar town.' where id = 19;
update moves set description = 'Things such as long bodies or tentacles are used to bind and squeeze the target for four to five turns.' where id = 20;
update moves set description = 'The target is slammed with a long tail, vines, or the like to inflict damage.' where id = 21;
update moves set description = 'The target is struck with slender, whiplike vines to inflict damage.' where id = 22;
update moves set description = 'The target is stomped with a big foot. This may also make the target flinch.' where id = 23;
update moves set description = 'The target is quickly kicked twice in succession using both feet.' where id = 24;
update moves set description = 'The target is attacked by a kick launched with muscle-packed power.' where id = 25;
update moves set description = 'The user jumps up high, then strikes with a kick. If the kick misses, the user hurts itself.' where id = 26;
update moves set description = 'The user lashes out with a quick, spinning kick. This may also make the target flinch.' where id = 27;
update moves set description = 'Sand is hurled in the target''s face, reducing the target''s accuracy.' where id = 28;
update moves set description = 'The user sticks out its head and attacks by charging straight into the target. This may also make the target flinch.' where id = 29;
update moves set description = 'The target is jabbed with a sharply pointed horn to inflict damage.' where id = 30;
update moves set description = 'The target is jabbed repeatedly with a horn or beak two to five times in a row.' where id = 31;
update moves set description = 'The user stabs the target with a horn that rotates like a drill. The target faints instantly if this attack hits.' where id = 32;
update moves set description = 'A physical attack in which the user charges and slams into the target with its whole body.' where id = 33;
update moves set description = 'The user drops onto the target with its full body weight. This may also leave the target with paralysis.' where id = 34;
update moves set description = 'A long body or vines are used to wrap and squeeze the target for four to five turns.' where id = 35;
update moves set description = 'A reckless, full-body charge attack for slamming into the target. This also damages the user a little.' where id = 36;
update moves set description = 'The user rampages and attacks for two to three turns. The user then becomes confused.' where id = 37;
update moves set description = 'A reckless, life-risking tackle. This also damages the user quite a lot.' where id = 38;
update moves set description = 'The user wags its tail cutely, making opposing Pokemon less wary and lowering their Defense stat.' where id = 39;
update moves set description = 'The user stabs the target with a poisonous stinger. This may also poison the target.' where id = 40;
update moves set description = 'The user damages the target twice in succession by jabbing it with two spikes. This may also poison the target.' where id = 41;
update moves set description = 'Sharp spikes are shot at the target in rapid succession. They hit two to five times in a row.' where id = 42;
update moves set description = 'The user gives opposing Pokemon an intimidating leer that lowers the Defense stat.' where id = 43;
update moves set description = 'The target is bitten with viciously sharp fangs. This may also make the target flinch.' where id = 44;
update moves set description = 'The user growls in an endearing way, making opposing Pokemon less wary. This lowers their Attack stats.' where id = 45;
update moves set description = 'The target is scared off, and a different Pokemon is dragged out. In the wild, this ends a battle against a single Pokemon.' where id = 46;
update moves set description = 'A soothing lullaby is sung in a calming voice that puts the target into a deep slumber.' where id = 47;
update moves set description = 'The user generates odd sound waves from its body that confuse the target.' where id = 48;
update moves set description = 'The target is hit with a destructive shock wave that always inflicts 20 HP damage.' where id = 49;
update moves set description = 'For four turns, this move prevents the target from using the move it last used.' where id = 50;
update moves set description = 'The opposing Pokemon are attacked with a spray of harsh acid. This may also lower their Sp. Def stats.' where id = 51;
update moves set description = 'The target is attacked with small flames. This may also leave the target with a burn.' where id = 52;
update moves set description = 'The target is scorched with an intense blast of fire. This may also leave the target with a burn.' where id = 53;
update moves set description = 'The user cloaks itself and its allies in a white mist that prevents any of their stats from being lowered for five turns.' where id = 54;
update moves set description = 'The target is blasted with a forceful shot of water.' where id = 55;
update moves set description = 'The target is blasted by a huge volume of water launched under great pressure.' where id = 56;
update moves set description = 'The user attacks everything around it by swamping its surroundings with a giant wave. This can also be used for crossing water.' where id = 57;
update moves set description = 'The target is struck with an icy-cold beam of energy. This may also leave the target frozen.' where id = 58;
update moves set description = 'A howling blizzard is summoned to strike opposing Pokemon. This may also leave the opposing Pokemon frozen.' where id = 59;
update moves set description = 'The target is attacked with a peculiar ray. This may also leave the target confused.' where id = 60;
update moves set description = 'A spray of bubbles is forcefully ejected at the target. This may also lower its Speed stat.' where id = 61;
update moves set description = 'The target is hit with a rainbow-colored beam. This may also lower the target''s Attack stat.' where id = 62;
update moves set description = 'The target is attacked with a powerful beam. The user can''t move on the next turn.' where id = 63;
update moves set description = 'The target is jabbed with a sharply pointed beak or horn.' where id = 64;
update moves set description = 'A corkscrewing attack with a sharp beak acting as a drill.' where id = 65;
update moves set description = 'The user grabs the target and recklessly dives for the ground. This also damages the user a little.' where id = 66;
update moves set description = 'A powerful low kick that makes the target fall over. The heavier the target, the greater the move''s power.' where id = 67;
update moves set description = 'A retaliation move that counters any physical attack, inflicting double the damage taken.' where id = 68;
update moves set description = 'The target is thrown using the power of gravity. It inflicts damage equal to the user''s level.' where id = 69;
update moves set description = 'The target is slugged with a punch thrown at maximum power. This can also be used to move heavy boulders.' where id = 70;
update moves set description = 'A nutrient-draining attack. The user''s HP is restored by half the damage taken by the target.' where id = 71;
update moves set description = 'A nutrient-draining attack. The user''s HP is restored by half the damage taken by the target.' where id = 72;
update moves set description = 'A seed is planted on the target. It steals some HP from the target every turn.' where id = 73;
update moves set description = 'The user''s body grows all at once, raising the Attack and Sp. Atk stats.' where id = 74;
update moves set description = 'Sharp-edged leaves are launched to slash at the opposing Pokemon. Critical hits land more easily.' where id = 75;
update moves set description = 'A two-turn attack. The user gathers light, then blasts a bundled beam on the next turn.' where id = 76;
update moves set description = 'The user scatters a cloud of poisonous dust on the target. This may also poison the target.' where id = 77;
update moves set description = 'The user scatters a cloud of numbing powder that paralyzes the target.' where id = 78;
update moves set description = 'The user scatters a big cloud of sleep-inducing dust around the target.' where id = 79;
update moves set description = 'The user attacks the target by scattering petals for two to three turns. The user then becomes confused.' where id = 80;
update moves set description = 'The opposing Pokemon are bound with silk blown from the user''s mouth that harshly lowers the Speed stat.' where id = 81;
update moves set description = 'This attack hits the target with a shock wave of pure rage. This attack always inflicts 40 HP damage.' where id = 82;
update moves set description = 'The target becomes trapped within a fierce vortex of fire that rages for four to five turns.' where id = 83;
update moves set description = 'A jolt of electricity crashes down on the target to inflict damage. This may also leave the target with paralysis.' where id = 84;
update moves set description = 'A strong electric blast crashes down on the target. This may also leave the target with paralysis.' where id = 85;
update moves set description = 'The user launches a weak jolt of electricity that paralyzes the target.' where id = 86;
update moves set description = 'A wicked thunderbolt is dropped on the target to inflict damage. This may also leave the target with paralysis.' where id = 87;
update moves set description = 'The user picks up and throws a small rock at the target to attack.' where id = 88;
update moves set description = 'The user sets off an earthquake that strikes every Pokemon around it.' where id = 89;
update moves set description = 'The user opens up a fissure in the ground and drops the target in. The target faints instantly if this attack hits.' where id = 90;
update moves set description = 'The user burrows, then attacks on the next turn. It can also be used to exit dungeons.' where id = 91;
update moves set description = 'A move that leaves the target badly poisoned. Its poison damage worsens every turn.' where id = 92;
update moves set description = 'The target is hit by a weak telekinetic force. This may also confuse the target.' where id = 93;
update moves set description = 'The target is hit by a strong telekinetic force. This may also lower the target''s Sp. Def stat.' where id = 94;
update moves set description = 'The user employs hypnotic suggestion to make the target fall into a deep sleep.' where id = 95;
update moves set description = 'The user meditates to awaken the power deep within its body and raise its Attack stat.' where id = 96;
update moves set description = 'The user relaxes and lightens its body to move faster. This sharply raises the Speed stat.' where id = 97;
update moves set description = 'The user lunges at the target at a speed that makes it almost invisible. This move always goes first.' where id = 98;
update moves set description = 'As long as this move is in use, the power of rage raises the Attack stat each time the user is hit in battle.' where id = 99;
update moves set description = 'Use it to flee from any wild Pokemon. It can also warp to the last Pokemon Center visited.' where id = 100;
update moves set description = 'The user makes the target see a frightening mirage. It inflicts damage equal to the user''s level.' where id = 101;
update moves set description = 'The user copies the target''s last move. The move can be used during battle until the Pokemon is switched out.' where id = 102;
update moves set description = 'An earsplitting screech harshly lowers the target''s Defense stat.' where id = 103;
update moves set description = 'By moving rapidly, the user makes illusory copies of itself to raise its evasiveness.' where id = 104;
update moves set description = 'Restoring its own cells, the user restores its own HP by half of its max HP.' where id = 105;
update moves set description = 'The user stiffens all the muscles in its body to raise its Defense stat.' where id = 106;
update moves set description = 'The user compresses its body to make itself look smaller, which sharply raises its evasiveness.' where id = 107;
update moves set description = 'The user releases an obscuring cloud of smoke or ink. This lowers the target''s accuracy.' where id = 108;
update moves set description = 'The target is exposed to a sinister ray that triggers confusion.' where id = 109;
update moves set description = 'The user withdraws its body into its hard shell, raising its Defense stat.' where id = 110;
update moves set description = 'The user curls up to conceal weak spots and raise its Defense stat.' where id = 111;
update moves set description = 'The user throws up a sturdy wall that sharply raises its Defense stat.' where id = 112;
update moves set description = 'A wondrous wall of light is put up to reduce damage from special attacks for five turns.' where id = 113;
update moves set description = 'The user creates a haze that eliminates every stat change among all the Pokemon engaged in battle.' where id = 114;
update moves set description = 'A wondrous wall of light is put up to reduce damage from physical attacks for five turns.' where id = 115;
update moves set description = 'The user takes a deep breath and focuses so that critical hits land more easily.' where id = 116;
update moves set description = 'The user endures attacks for two turns, then strikes back to cause double the damage taken.' where id = 117;
update moves set description = 'The user waggles a finger and stimulates its brain into randomly using nearly any move.' where id = 118;
update moves set description = 'The user counters the target by mimicking the target''s last move.' where id = 119;
update moves set description = 'The user attacks everything around it by causing an explosion. The user faints upon using this move.' where id = 120;
update moves set description = 'A large egg is hurled at the target with maximum force to inflict damage.' where id = 121;
update moves set description = 'The target is licked with a long tongue, causing damage. This may also leave the target with paralysis.' where id = 122;
update moves set description = 'The target is attacked with a discharge of filthy gases. This may also poison the target.' where id = 123;
update moves set description = 'Unsanitary sludge is hurled at the target. This may also poison the target.' where id = 124;
update moves set description = 'The user clubs the target with a bone. This may also make the target flinch.' where id = 125;
update moves set description = 'The target is attacked with an intense blast of all-consuming fire. This may also leave the target with a burn.' where id = 126;
update moves set description = 'The user charges at the target and may make it flinch. This can also be used to climb a waterfall.' where id = 127;
update moves set description = 'The target is clamped and squeezed by the user''s very thick and sturdy shell for four to five turns.' where id = 128;
update moves set description = 'Star-shaped rays are shot at the opposing Pokemon. This attack never misses.' where id = 129;
update moves set description = 'The user tucks in its head to raise its Defense in the first turn, then rams the target on the next turn.' where id = 130;
update moves set description = 'Sharp spikes are shot at the target in rapid succession. They hit two to five times in a row.' where id = 131;
update moves set description = 'The target is attacked with long, creeping tentacles or vines. This may also lower the target''s Speed stat.' where id = 132;
update moves set description = 'The user temporarily empties its mind to forget its concerns. This sharply raises the user''s Sp. Def stat.' where id = 133;
update moves set description = 'The user distracts the target by bending a spoon. This lowers the target''s accuracy.' where id = 134;
update moves set description = 'The user restores its own HP by up to half of its max HP. May also be used in the field to heal HP.' where id = 135;
update moves set description = 'The target is attacked with a knee kick from a jump. If it misses, the user is hurt instead.' where id = 136;
update moves set description = 'The user intimidates the target with the pattern on its belly to cause paralysis.' where id = 137;
update moves set description = 'The user eats the dreams of a sleeping target. It absorbs half the damage caused to heal its own HP.' where id = 138;
update moves set description = 'A cloud of poison gas is sprayed in the face of opposing Pokemon. This may also poison those hit.' where id = 139;
update moves set description = 'Round objects are hurled at the target to strike two to five times in a row.' where id = 140;
update moves set description = 'The user drains the target''s blood. The user''s HP is restored by half the damage taken by the target.' where id = 141;
update moves set description = 'With a scary face, the user tries to force a kiss on the target. If it succeeds, the target falls asleep.' where id = 142;
update moves set description = 'A second-turn attack move where critical hits land more easily. This may also make the target flinch.' where id = 143;
update moves set description = 'The user transforms into a copy of the target right down to having the same move set.' where id = 144;
update moves set description = 'A spray of countless bubbles is jetted at the opposing Pokemon. This may also lower their Speed stats.' where id = 145;
update moves set description = 'The target is hit with rhythmically launched punches. This may also leave the target confused.' where id = 146;
update moves set description = 'The user scatters bursts of spores that induce sleep.' where id = 147;
update moves set description = 'The user flashes a bright light that cuts the target''s accuracy. It can also be used to illuminate dark caves.' where id = 148;
update moves set description = 'The target is attacked with an odd psychic wave. The attack varies in intensity.' where id = 149;
update moves set description = 'The user just flops and splashes around to no effect at all...' where id = 150;
update moves set description = 'The user alters its cellular structure to liquefy itself, sharply raising its Defense stat.' where id = 151;
update moves set description = 'The target is hammered with a large pincer. Critical hits land more easily.' where id = 152;
update moves set description = 'The user attacks everything around it by causing a tremendous explosion. The user faints upon using this move.' where id = 153;
update moves set description = 'The target is raked with sharp claws or scythes quickly two to five times in a row.' where id = 154;
update moves set description = 'The user throws the bone it holds. The bone loops to hit the target twice, coming and going.' where id = 155;
update moves set description = 'The user goes to sleep for two turns. This fully restores the user''s HP and heals any status conditions.' where id = 156;
update moves set description = 'Large boulders are hurled at the opposing Pokemon to inflict damage. This may also make the opposing Pokemon flinch.' where id = 157;
update moves set description = 'The user bites hard on the target with its sharp front fangs. This may also make the target flinch.' where id = 158;
update moves set description = 'The user lowers its polygon count to make itself more jagged, raising the Attack stat.' where id = 159;
update moves set description = 'The user changes its type to become the same type as the move at the top of the list of moves it knows.' where id = 160;
update moves set description = 'The user strikes with a simultaneous three-beam attack. May also burn, freeze, or leave the target with paralysis.' where id = 161;
update moves set description = 'The user chomps hard on the target with its sharp front fangs. This cuts the target''s HP in half.' where id = 162;
update moves set description = 'The target is attacked with a slash of claws or blades. Critical hits land more easily.' where id = 163;
update moves set description = 'The user makes a copy of itself using some of its HP. The copy serves as the user''s decoy.' where id = 164;
update moves set description = 'An attack that is used in desperation only if the user has no PP. This also damages the user a little.' where id = 165;
update moves set description = 'It enables the user to permanently learn the move last used by the target. Once used, Sketch disappears.' where id = 166;
update moves set description = 'A consecutive three-kick attack that becomes more powerful with each successive hit.' where id = 167;
update moves set description = 'The user attacks and steals the target''s held item simultaneously. The user can''t steal anything if it already holds an item.' where id = 168;
update moves set description = 'The user ensnares the target with thin, gooey silk so it can''t flee from battle.' where id = 169;
update moves set description = 'The user senses the target''s movements with its mind to ensure its next attack does not miss the target.' where id = 170;
update moves set description = 'A sleeping target sees a nightmare that inflicts some damage every turn.' where id = 171;
update moves set description = 'The user cloaks itself in fire and charges at the target. This may also leave the target with a burn.' where id = 172;
update moves set description = 'An attack that can be used only if the user is asleep. The harsh noise may also make the target flinch.' where id = 173;
update moves set description = 'A move that works differently for the Ghost type than for all other types.' where id = 174;
update moves set description = 'The user flails about aimlessly to attack. The less HP the user has, the greater the move''s power.' where id = 175;
update moves set description = 'The user changes its type to make itself resistant to the type of the attack the opponent used last.' where id = 176;
update moves set description = 'A vortex of air is shot at the target to inflict damage. Critical hits land more easily.' where id = 177;
update moves set description = 'The user releases cotton-like spores that cling to the opposing Pokemon, which harshly lowers their Speed stats.' where id = 178;
update moves set description = 'An all-out attack that becomes more powerful the less HP the user has.' where id = 179;
update moves set description = 'The user unleashes its grudge on the move last used by the target by cutting 4 PP from it.' where id = 180;
update moves set description = 'The user attacks with a chilling gust of powdery snow. This may also freeze the opposing Pokemon.' where id = 181;
update moves set description = 'Enables the user to evade all attacks. Its chance of failing rises if it is used in succession.' where id = 182;
update moves set description = 'The user throws a punch at blinding speed. This move always goes first.' where id = 183;
update moves set description = 'The user frightens the target with a scary face to harshly lower its Speed stat.' where id = 184;
update moves set description = 'The user approaches the target disarmingly, then throws a sucker punch. This attack never misses.' where id = 185;
update moves set description = 'The user kisses the target with a sweet, angelic cuteness that causes confusion.' where id = 186;
update moves set description = 'The user maximizes its Attack stat in exchange for HP equal to half its max HP.' where id = 187;
update moves set description = 'Unsanitary sludge is hurled at the target. This may also poison the target.' where id = 188;
update moves set description = 'The user hurls mud in the target''s face to inflict damage and lower its accuracy.' where id = 189;
update moves set description = 'The user attacks by spraying ink in the target''s face or eyes. This may also lower the target''s accuracy.' where id = 190;
update moves set description = 'The user lays a trap of spikes at the opposing team''s feet. The trap hurts Pokemon that switch into battle.' where id = 191;
update moves set description = 'The user fires an electric blast like a cannon to inflict damage and cause paralysis.' where id = 192;
update moves set description = 'Enables a Ghost-type target to be hit by Normal- and Fighting-type attacks. This also enables an evasive target to be hit.' where id = 193;
update moves set description = 'When this move is used, if the user faints, the Pokemon that landed the knockout hit also faints.' where id = 194;
update moves set description = 'Any Pokemon that hears this song faints in three turns, unless it switches out of battle.' where id = 195;
update moves set description = 'The user attacks with a gust of chilled air. This also lowers the opposing Pokemon''s Speed stats.' where id = 196;
update moves set description = 'Enables the user to evade all attacks. Its chance of failing rises if it is used in succession.' where id = 197;
update moves set description = 'The user strikes the target with a hard bone two to five times in a row.' where id = 198;
update moves set description = 'The user takes sure aim at the target. This ensures the next attack does not miss the target.' where id = 199;
update moves set description = 'The user rampages and attacks for two to three turns. The user then becomes confused.' where id = 200;
update moves set description = 'A five-turn sandstorm is summoned to hurt all combatants except the Rock, Ground, and Steel types.' where id = 201;
update moves set description = 'A nutrient-draining attack. The user''s HP is restored by half the damage taken by the target.' where id = 202;
update moves set description = 'The user endures any attack with at least 1 HP. Its chance of failing rises if it is used in succession.' where id = 203;
update moves set description = 'The user gazes at the target rather charmingly, making it less wary. This harshly lowers its Attack stat.' where id = 204;
update moves set description = 'The user continually rolls into the target over five turns. It becomes more powerful each time it hits.' where id = 205;
update moves set description = 'A restrained attack that prevents the target from fainting. The target is left with at least 1 HP.' where id = 206;
update moves set description = 'The user enrages and confuses the target. However, this also sharply raises the target''s Attack stat.' where id = 207;
update moves set description = 'The user restores its own HP by up to half of its max HP. May also be used in the field to heal HP.' where id = 208;
update moves set description = 'The user throws an electrically charged tackle at the target. This may also leave the target with paralysis.' where id = 209;
update moves set description = 'The target is slashed with scythes or claws. This attack becomes more powerful if it hits in succession.' where id = 210;
update moves set description = 'The target is hit with wings of steel. This may also raise the user''s Defense stat.' where id = 211;
update moves set description = 'The user pins the target with a dark, arresting look. The target becomes unable to flee.' where id = 212;
update moves set description = 'If it is the opposite gender of the user, the target becomes infatuated and less likely to attack.' where id = 213;
update moves set description = 'While it is asleep, the user randomly uses one of the moves it knows.' where id = 214;
update moves set description = 'The user makes a soothing bell chime to heal the status conditions of all the party Pokemon.' where id = 215;
update moves set description = 'A full-power attack that grows more powerful the more the user likes its Trainer.' where id = 216;
update moves set description = 'The user attacks by giving the target a gift with a hidden trap. It restores HP sometimes, however.' where id = 217;
update moves set description = 'A full-power attack that grows more powerful the less the user likes its Trainer.' where id = 218;
update moves set description = 'The user creates a protective field that prevents status conditions for five turns.' where id = 219;
update moves set description = 'The user adds its HP to the target''s HP, then equally shares the combined HP with the target.' where id = 220;
update moves set description = 'The target is razed with a mystical fire of great intensity. This may also leave the target with a burn.' where id = 221;
update moves set description = 'The user attacks everything around it with a ground-shaking quake. Its power varies.' where id = 222;
update moves set description = 'The user punches the target with full, concentrated power. This confuses the target if it hits.' where id = 223;
update moves set description = 'Using its tough and impressive horn, the user rams into the target with no letup.' where id = 224;
update moves set description = 'The user exhales a mighty gust that inflicts damage. This may also leave the target with paralysis.' where id = 225;
update moves set description = 'The user switches places with a party Pokemon in waiting and passes along any stat changes.' where id = 226;
update moves set description = 'The user compels the target to keep using only the move it last used for three turns.' where id = 227;
update moves set description = 'An attack move that inflicts double damage if used on a target that is switching out of battle.' where id = 228;
update moves set description = 'A spin attack that can also eliminate such moves as Bind, Wrap, Leech Seed, and Spikes.' where id = 229;
update moves set description = 'A sweet scent that harshly lowers opposing Pokemon''s evasiveness. This also lures wild Pokemon if used in places such as tall grass.' where id = 230;
update moves set description = 'The target is slammed with a steel-hard tail. This may also lower the target''s Defense stat.' where id = 231;
update moves set description = 'The target is raked with steel claws. This may also raise the user''s Attack stat.' where id = 232;
update moves set description = 'The user attacks last. In return, this throw move never misses.' where id = 233;
update moves set description = 'The user restores its own HP. The amount of HP regained varies with the weather.' where id = 234;
update moves set description = 'The user restores its own HP. The amount of HP regained varies with the weather.' where id = 235;
update moves set description = 'The user restores its own HP. The amount of HP regained varies with the weather.' where id = 236;
update moves set description = 'A unique attack that varies in type depending on the Pokemon using it.' where id = 237;
update moves set description = 'The user delivers a double chop with its forearms crossed. Critical hits land more easily.' where id = 238;
update moves set description = 'The user whips up a vicious tornado to tear at the opposing Pokemon. This may also make them flinch.' where id = 239;
update moves set description = 'The user summons a heavy rain that falls for five turns, powering up Water-type moves.' where id = 240;
update moves set description = 'The user intensifies the sun for five turns, powering up Fire-type moves.' where id = 241;
update moves set description = 'The user crunches up the target with sharp fangs. This may also lower the target''s Defense stat.' where id = 242;
update moves set description = 'A retaliation move that counters any special attack, inflicting double the damage taken.' where id = 243;
update moves set description = 'The user hypnotizes itself into copying any stat change made by the target.' where id = 244;
update moves set description = 'The user charges the target at blinding speed. This move always goes first.' where id = 245;
update moves set description = 'The user attacks with a prehistoric power. This may also raise all the user''s stats at once.' where id = 246;
update moves set description = 'The user hurls a shadowy blob at the target. This may also lower the target''s Sp. Def stat.' where id = 247;
update moves set description = 'Two turns after this move is used, a hunk of psychic energy attacks the target.' where id = 248;
update moves set description = 'The user attacks with a punch. This may also lower the target''s Defense stat. This move can also shatter rocks in the field.' where id = 249;
update moves set description = 'The user traps the target in a violent swirling whirlpool for four to five turns.' where id = 250;
update moves set description = 'The user gets all party Pokemon to attack the target. The more party Pokemon, the greater the number of attacks.' where id = 251;
update moves set description = 'An attack that hits first and makes the target flinch. It only works the first turn the user is in battle.' where id = 252;
update moves set description = 'The user attacks in an uproar for three turns. During that time, no one can fall asleep.' where id = 253;
update moves set description = 'The user charges up power and raises both its Defense and Sp. Def stats. The move can be used three times.' where id = 254;
update moves set description = 'The power stored using the move Stockpile is released at once in an attack. The more power is stored, the greater the move''s power.' where id = 255;
update moves set description = 'The power stored using the move Stockpile is absorbed by the user to heal its HP. Storing more power heals more HP.' where id = 256;
update moves set description = 'The user attacks by exhaling hot breath on the opposing Pokemon. This may also leave those Pokemon with a burn.' where id = 257;
update moves set description = 'The user summons a hailstorm lasting five turns. It damages all Pokemon except the Ice type.' where id = 258;
update moves set description = 'The user torments and enrages the target, making it incapable of using the same move twice in a row.' where id = 259;
update moves set description = 'Flattery is used to confuse the target. However, this also raises the target''s Sp. Atk stat.' where id = 260;
update moves set description = 'The user shoots a sinister, bluish-white flame at the target to inflict a burn.' where id = 261;
update moves set description = 'The user faints when using this move. In return, this harshly lowers the target''s Attack and Sp. Atk stats.' where id = 262;
update moves set description = 'An attack move that doubles its power if the user is poisoned, burned, or has paralysis.' where id = 263;
update moves set description = 'The user focuses its mind before launching a punch. This move fails if the user is hit before it is used.' where id = 264;
update moves set description = 'This attack inflicts double damage on a target with paralysis. This also cures the target''s paralysis, however.' where id = 265;
update moves set description = 'The user draws attention to itself, making all targets take aim only at the user.' where id = 266;
update moves set description = 'An attack that makes use of nature''s power. Its effects vary depending on the user''s environment.' where id = 267;
update moves set description = 'The user boosts the power of the Electric move it uses on the next turn. This also raises the user''s Sp. Def stat.' where id = 268;
update moves set description = 'The target is taunted into a rage that allows it to use only attack moves for three turns.' where id = 269;
update moves set description = 'The user assists an ally by boosting the power of that ally''s attack.' where id = 270;
update moves set description = 'The user catches the target off guard and swaps its held item with its own.' where id = 271;
update moves set description = 'The user mimics the target completely, copying the target''s natural Ability.' where id = 272;
update moves set description = 'One turn after this move is used, the target''s HP is restored by half the user''s max HP.' where id = 273;
update moves set description = 'The user hurriedly and randomly uses a move among those known by other Pokemon in the party.' where id = 274;
update moves set description = 'The user lays roots that restore its HP on every turn. Because it is rooted, it can''t switch out.' where id = 275;
update moves set description = 'The user attacks the target with great power. However, this also lowers the user''s Attack and Defense stats.' where id = 276;
update moves set description = 'A barrier reflects back to the target moves like Leech Seed and moves that damage status.' where id = 277;
update moves set description = 'The user recycles a held item that has been used in battle so it can be used again.' where id = 278;
update moves set description = 'An attack move that inflicts double the damage if the user has been hurt by the opponent in the same turn.' where id = 279;
update moves set description = 'The user attacks with a swift chop. It can also break barriers, such as Light Screen and Reflect.' where id = 280;
update moves set description = 'The user lets loose a huge yawn that lulls the target into falling asleep on the next turn.' where id = 281;
update moves set description = 'The user slaps down the target''s held item, and that item can''t be used in that battle. The move does more damage if the target has a held item.' where id = 282;
update moves set description = 'An attack move that cuts down the target''s HP to equal the user''s HP.' where id = 283;
update moves set description = 'The user attacks opposing Pokemon with explosive fury. The lower the user''s HP, the lower the move''s power.' where id = 284;
update moves set description = 'The user employs its psychic power to exchange Abilities with the target.' where id = 285;
update moves set description = 'If opposing Pokemon know any move also known by the user, they are prevented from using it.' where id = 286;
update moves set description = 'The user rests to cure itself of a poisoning, burn, or paralysis.' where id = 287;
update moves set description = 'If the user faints, the user''s grudge fully depletes the PP of the opponent''s move that knocked it out.' where id = 288;
update moves set description = 'The user steals the effects of any attempts to use a healing or stat-changing move.' where id = 289;
update moves set description = 'An attack whose additional effects depend upon where it was used. Can also be used to make a Secret Base.' where id = 290;
update moves set description = 'Diving on the first turn, the user floats up and attacks on the next turn. It can be used to dive deep in the ocean.' where id = 291;
update moves set description = 'The user lets loose a flurry of open-palmed arm thrusts that hit two to five times in a row.' where id = 292;
update moves set description = 'The user''s type is changed depending on its environment, such as at water''s edge, in grass, or in a cave.' where id = 293;
update moves set description = 'The user stares at flashing lights to focus its mind, drastically raising its Sp. Atk stat.' where id = 294;
update moves set description = 'The user lets loose a damaging burst of light. This may also lower the target''s Sp. Def stat.' where id = 295;
update moves set description = 'A mist-like flurry of down envelops and damages the target. This may also lower the target''s Sp. Atk stat.' where id = 296;
update moves set description = 'The user covers the target''s body with a mass of down that harshly lowers its Attack stat.' where id = 297;
update moves set description = 'The user performs a wobbly dance that confuses the Pokemon around it.' where id = 298;
update moves set description = 'The user launches a kick that lands a critical hit more easily. This may also leave the target with a burn.' where id = 299;
update moves set description = 'The user covers itself with mud. This weakens Electric-type moves for five turns.' where id = 300;
update moves set description = 'The user continually rolls into the target over five turns. It becomes stronger each time it hits.' where id = 301;
update moves set description = 'The user attacks by wildly swinging its thorny arms. This may also make the target flinch.' where id = 302;
update moves set description = 'The user slacks off, restoring its own HP by up to half of its max HP.' where id = 303;
update moves set description = 'The user lets loose a horribly echoing shout with the power to inflict damage.' where id = 304;
update moves set description = 'The user bites the target with toxic fangs. This may also leave the target badly poisoned.' where id = 305;
update moves set description = 'The user slashes the target with hard and sharp claws. This may also lower the target''s Defense stat.' where id = 306;
update moves set description = 'The target is razed by a fiery explosion. The user can''t move on the next turn.' where id = 307;
update moves set description = 'The target is hit with a watery blast. The user can''t move on the next turn.' where id = 308;
update moves set description = 'The target is hit with a hard punch fired like a meteor. This may also raise the user''s Attack stat.' where id = 309;
update moves set description = 'The user attacks the target while shouting in a startling fashion. This may also make the target flinch.' where id = 310;
update moves set description = 'An attack move that varies in power and type depending on the weather.' where id = 311;
update moves set description = 'The user releases a soothing scent that heals all status conditions affecting the user''s party.' where id = 312;
update moves set description = 'The user feigns crying to fluster the target, harshly lowering its Sp. Def stat.' where id = 313;
update moves set description = 'The user launches razor-like wind to slash the opposing Pokemon. Critical hits land more easily.' where id = 314;
update moves set description = 'The user attacks the target at full power. The attack''s recoil harshly lowers the user''s Sp. Atk stat.' where id = 315;
update moves set description = 'Enables a Ghost-type target to be hit by Normal- and Fighting-type attacks. This also enables an evasive target to be hit.' where id = 316;
update moves set description = 'Boulders are hurled at the target. This also lowers the target''s Speed stat by preventing its movement.' where id = 317;
update moves set description = 'The target is attacked with powdery scales blown by wind. This may also raise all the user''s stats.' where id = 318;
update moves set description = 'A horrible sound like scraping metal harshly lowers the target''s Sp. Def stat.' where id = 319;
update moves set description = 'The user plays a pleasant melody that lulls the target into a deep sleep.' where id = 320;
update moves set description = 'The user tickles the target into laughing, reducing its Attack and Defense stats.' where id = 321;
update moves set description = 'The user absorbs a mystical power from space to raise its Defense and Sp. Def stats.' where id = 322;
update moves set description = 'The user spouts water to damage opposing Pokemon. The lower the user''s HP, the lower the move''s power.' where id = 323;
update moves set description = 'The user attacks with a sinister beam of light. This may also confuse the target.' where id = 324;
update moves set description = 'The user throws a punch from the shadows. This attack never misses.' where id = 325;
update moves set description = 'The user attacks with an odd, unseeable power. This may also make the target flinch.' where id = 326;
update moves set description = 'The user attacks the target with an uppercut thrown skyward with force.' where id = 327;
update moves set description = 'The user traps the target inside a harshly raging sandstorm for four to five turns.' where id = 328;
update moves set description = 'The target is attacked with a blast of absolute-zero cold. The target faints instantly if this attack hits.' where id = 329;
update moves set description = 'The user attacks by shooting muddy water at the opposing Pokemon. This may also lower their accuracy.' where id = 330;
update moves set description = 'The user forcefully shoots seeds at the target two to five times in a row.' where id = 331;
update moves set description = 'The user confounds the target with speed, then slashes. This attack never misses' where id = 332;
update moves set description = 'The user launches sharp icicles at the target two to five times in a row.' where id = 333;
update moves set description = 'The user hardens its body''s surface like iron, sharply raising its Defense stat.' where id = 334;
update moves set description = 'The user blocks the target''s way with arms spread wide to prevent escape.' where id = 335;
update moves set description = 'The user howls loudly to raise its spirit, which raises its Attack stat.' where id = 336;
update moves set description = 'The user slashes the target with huge, sharp claws.' where id = 337;
update moves set description = 'The user slams the target with an enormous tree. The user can''t move on the next turn.' where id = 338;
update moves set description = 'The user tenses its muscles to bulk up its body, raising both its Attack and Defense stats.' where id = 339;
update moves set description = 'The user bounces up high, then drops on the target on the second turn. This may also leave the target with paralysis.' where id = 340;
update moves set description = 'The user attacks by hurling a blob of mud at the target. This also lowers the target''s Speed stat.' where id = 341;
update moves set description = 'The user hits the target with its tail. This may also poison the target. Critical hits land more easily.' where id = 342;
update moves set description = 'The user endearingly approaches the target, then steals the target''s held item.' where id = 343;
update moves set description = 'The user electrifies itself, then charges. This also damages the user quite a lot. This may leave the target with paralysis.' where id = 344;
update moves set description = 'The user scatters curious leaves that chase the target. This attack never misses.' where id = 345;
update moves set description = 'The user soaks itself with water. This weakens Fire-type moves for five turns.' where id = 346;
update moves set description = 'The user quietly focuses its mind and calms its spirit to raise its Sp. Atk and Sp. Def stats.' where id = 347;
update moves set description = 'The user handles a sharp leaf like a sword and attacks by cutting its target. Critical hits land more easily.' where id = 348;
update moves set description = 'The user vigorously performs a mystic, powerful dance that raises its Attack and Speed stats.' where id = 349;
update moves set description = 'The user hurls hard rocks at the target. Two to five rocks are launched in a row.' where id = 350;
update moves set description = 'The user strikes the target with a quick jolt of electricity. This attack never misses.' where id = 351;
update moves set description = 'The user attacks the target with a pulsing blast of water. This may also confuse the target.' where id = 352;
update moves set description = 'Two turns after this move is used, the user blasts the target with a concentrated bundle of light.' where id = 353;
update moves set description = 'The user attacks the target at full power. The attack''s recoil harshly lowers the user''s Sp. Atk stat' where id = 354;
update moves set description = 'The user lands and rests its body. It restores the user''s HP by up to half of its max HP.' where id = 355;
update moves set description = 'Gravity is intensified for five turns, making moves involving flying unusable and negating Levitate.' where id = 356;
update moves set description = 'Enables a Dark-type target to be hit by Psychic-type attacks. This also enables an evasive target to be hit.' where id = 357;
update moves set description = 'This attack inflicts big damage on a sleeping target. This also wakes the target up, however.' where id = 358;
update moves set description = 'The user swings and hits with its strong and heavy fist. It lowers the user''s Speed, however.' where id = 359;
update moves set description = 'The user tackles the target with a high-speed spin. The slower the user compared to the target, the greater the move''s power.' where id = 360;
update moves set description = 'The user faints. In return, the Pokemon taking its place will have its HP restored and status conditions cured.' where id = 361;
update moves set description = 'If the target''s HP is half or less, this attack will hit with double the power.' where id = 362;
update moves set description = 'The user draws power to attack by using its held Berry. The Berry determines the move''s type and power.' where id = 363;
update moves set description = 'An attack that hits a target using Protect or Detect. This also lifts the effects of those moves.' where id = 364;
update moves set description = 'The user pecks the target. If the target is holding a Berry, the user eats it and gains its effect.' where id = 365;
update moves set description = 'The user whips up a turbulent whirlwind that ups the Speed stat of the user and its allies for four turns.' where id = 366;
update moves set description = 'The user applies pressure to stress points, sharply boosting one of its or its allies'' stats.' where id = 367;
update moves set description = 'The user retaliates with much greater power against the opponent that last inflicted damage on it.' where id = 368;
update moves set description = 'After making its attack, the user rushes back to switch places with a party Pokemon in waiting.' where id = 369;
update moves set description = 'The user fights the target up close without guarding itself. This also lowers the user''s Defense and Sp. Def stats.' where id = 370;
update moves set description = 'The user stores power, then attacks. If the user moves after the target, this attack''s power will be doubled.' where id = 371;
update moves set description = 'If the target has already taken some damage in the same turn, this attack''s power is doubled.' where id = 372;
update moves set description = 'This move prevents the target from using its held item. Its Trainer is also prevented from using items on it.' where id = 373;
update moves set description = 'The user flings its held item at the target to attack. This move''s power and effects depend on the item.' where id = 374;
update moves set description = 'Using its psychic power of suggestion, the user transfers its status conditions to the target.' where id = 375;
update moves set description = 'The fewer PP this move has, the greater its power.' where id = 376;
update moves set description = 'For five turns, the user prevents the opposing team from using any moves, Abilities, or held items that recover HP.' where id = 377;
update moves set description = 'The user powerfully wrings the target. The more HP the target has, the greater the move''s power.' where id = 378;
update moves set description = 'The user employs its psychic power to switch its Attack with its Defense stat.' where id = 379;
update moves set description = 'The user hurls up its stomach acids on the target. The fluid eliminates the effect of the target''s Ability.' where id = 380;
update moves set description = 'The user chants an incantation toward the sky, preventing opposing Pokemon from landing critical hits.' where id = 381;
update moves set description = 'The user cuts ahead of the target to steal and use the target''s intended move with greater power. This move fails if it isn''t used first.' where id = 382;
update moves set description = 'The user mimics the move used immediately before it. The move fails if no other move has been used yet.' where id = 383;
update moves set description = 'The user employs its psychic power to switch changes to its Attack and Sp. Atk stats with the target.' where id = 384;
update moves set description = 'The user employs its psychic power to switch changes to its Defense and Sp. Def stats with the target.' where id = 385;
update moves set description = 'The more the target has powered up with stat changes, the greater the move''s power.' where id = 386;
update moves set description = 'This move can be used only after the user has used all the other moves it knows in the battle.' where id = 387;
update moves set description = 'A seed that causes worry is planted on the target. It prevents sleep by making the target''s Ability Insomnia.' where id = 388;
update moves set description = 'This move enables the user to attack first. This move fails if the target is not readying an attack.' where id = 389;
update moves set description = 'The user lays a trap of poison spikes at the opposing team''s feet. They poison opposing Pokemon that switch into battle.' where id = 390;
update moves set description = 'The user employs its psychic power to switch stat changes with the target.' where id = 391;
update moves set description = 'The user envelops itself in a veil made of water. It regains some HP every turn.' where id = 392;
update moves set description = 'The user levitates using electrically generated magnetism for five turns.' where id = 393;
update moves set description = 'The user cloaks itself in fire and charges the target. This also damages the user quite a lot. This may leave the target with a burn.' where id = 394;
update moves set description = 'The target is attacked with a shock wave. This may also leave the target with paralysis.' where id = 395;
update moves set description = 'The user lets loose a blast of aura power from deep within its body at the target. This attack never misses.' where id = 396;
update moves set description = 'The user polishes its body to reduce drag. This can sharply raise the Speed stat.' where id = 397;
update moves set description = 'The target is stabbed with a tentacle or arm steeped in poison. This may also poison the target.' where id = 398;
update moves set description = 'The user releases a horrible aura imbued with dark thoughts. This may also make the target flinch.' where id = 399;
update moves set description = 'The user slashes the target the instant an opportunity arises. Critical hits land more easily.' where id = 400;
update moves set description = 'The user attacks by swinging its tail as if it were a vicious wave in a raging storm.' where id = 401;
update moves set description = 'The user slams a barrage of hard-shelled seeds down on the target from above.' where id = 402;
update moves set description = 'The user attacks with a blade of air that slices even the sky. This may also make the target flinch.' where id = 403;
update moves set description = 'The user slashes at the target by crossing its scythes or claws as if they were a pair of scissors.' where id = 404;
update moves set description = 'The user vibrates its wings to generate a damaging sound wave. This may also lower the target''s Sp. Def stat.' where id = 405;
update moves set description = 'The target is attacked with a shock wave generated by the user''s gaping mouth.' where id = 406;
update moves set description = 'The user tackles the target while exhibiting overwhelming menace. This may also make the target flinch.' where id = 407;
update moves set description = 'The user attacks with a ray of light that sparkles as if it were made of gemstones.' where id = 408;
update moves set description = 'An energy-draining punch. The user''s HP is restored by half the damage taken by the target.' where id = 409;
update moves set description = 'The user whirls its fists to send a wave of pure vacuum at the target. This move always goes first.' where id = 410;
update moves set description = 'The user heightens its mental focus and unleashes its power. This may also lower the target''s Sp. Def.' where id = 411;
update moves set description = 'The user draws power from nature and fires it at the target. This may also lower the target''s Sp. Def.' where id = 412;
update moves set description = 'The user tucks in its wings and charges from a low altitude. This also damages the user quite a lot.' where id = 413;
update moves set description = 'The user makes the ground under the target erupt with power. This may also lower the target''s Sp. Def.' where id = 414;
update moves set description = 'The user trades held items with the target faster than the eye can follow.' where id = 415;
update moves set description = 'The user charges at the target using every bit of its power. The user can''t move on the next turn.' where id = 416;
update moves set description = 'The user stimulates its brain by thinking bad thoughts. This sharply raises the user''s Sp. Atk.' where id = 417;
update moves set description = 'The user strikes the target with tough punches as fast as bullets. This move always goes first.' where id = 418;
update moves set description = 'An attack move that inflicts double the damage if the user has been hurt by the target in the same turn.' where id = 419;
update moves set description = 'The user flash-freezes chunks of ice and hurls them at the target. This move always goes first.' where id = 420;
update moves set description = 'The user slashes with a sharp claw made from shadows. Critical hits land more easily.' where id = 421;
update moves set description = 'The user bites with electrified fangs. This may also make the target flinch or leave it with paralysis.' where id = 422;
update moves set description = 'The user bites with cold-infused fangs. This may also make the target flinch or leave it frozen.' where id = 423;
update moves set description = 'The user bites with flame-cloaked fangs. This may also make the target flinch or leave it with a burn.' where id = 424;
update moves set description = 'The user extends its shadow and attacks the target from behind. This move always goes first.' where id = 425;
update moves set description = 'The user launches a hard-packed mud ball to attack. This may also lower the target''s accuracy.' where id = 426;
update moves set description = 'The user tears at the target with blades formed by psychic power. Critical hits land more easily.' where id = 427;
update moves set description = 'The user focuses its willpower to its head and attacks the target. This may also make the target flinch.' where id = 428;
update moves set description = 'The user lets loose a flash of energy at the target from its polished body. This may also lower the target''s accuracy.' where id = 429;
update moves set description = 'The user gathers all its light energy and releases it at once. This may also lower the target''s Sp. Def stat.' where id = 430;
update moves set description = 'The user attacks the target by smashing into it with incredible force. This may also confuse the target.' where id = 431;
update moves set description = 'A strong wind blows away the target''s barriers such as Reflect or Light Screen. This also lowers the target''s evasiveness.' where id = 432;
update moves set description = 'The user creates a bizarre area in which slower Pokemon get to move first for five turns.' where id = 433;
update moves set description = 'Comets are summoned down from the sky onto the target. The attack''s recoil harshly lowers the user''s Sp. Atk stat.' where id = 434;
update moves set description = 'The user strikes everything around it by letting loose a flare of electricity. This may also cause paralysis.' where id = 435;
update moves set description = 'The user torches everything around it with an inferno of scarlet flames. This may also leave those hit with a burn.' where id = 436;
update moves set description = 'The user whips up a storm of leaves around the target. The attack''s recoil harshly lowers the user''s Sp. Atk stat.' where id = 437;
update moves set description = 'The user violently whirls its vines or tentacles to harshly lash the target.' where id = 438;
update moves set description = 'The user launches a huge boulder at the target to attack. The user can''t move on the next turn.' where id = 439;
update moves set description = 'A slashing attack with a poisonous blade that may also poison the target. Critical hits land more easily.' where id = 440;
update moves set description = 'The user shoots filthy garbage at the target to attack. This may also poison the target.' where id = 441;
update moves set description = 'The user slams the target with its steel-hard head. This may also make the target flinch.' where id = 442;
update moves set description = 'The user launches steel bombs that stick to the target. This attack never misses.' where id = 443;
update moves set description = 'The user stabs the target with sharpened stones from below. Critical hits land more easily.' where id = 444;
update moves set description = 'If any opposing Pokemon is the opposite gender of the user, it is charmed, which harshly lowers its Sp. Atk stat.' where id = 445;
update moves set description = 'The user lays a trap of levitating stones around the opposing team. The trap hurts opposing Pokemon that switch into battle.' where id = 446;
update moves set description = 'The user snares the target with grass and trips it. The heavier the target, the greater the move''s power.' where id = 447;
update moves set description = 'The user attacks the target with sound waves of deafening chatter. This confuses the target.' where id = 448;
update moves set description = 'The user releases countless shots of light at the target. This move''s type varies depending on the kind of Plate the user is holding.' where id = 449;
update moves set description = 'The user bites the target. If the target is holding a Berry, the user eats it and gains its effect.' where id = 450;
update moves set description = 'The user attacks with an electric charge. The user may use any remaining electricity to raise its Sp. Atk stat.' where id = 451;
update moves set description = 'The user slams its rugged body into the target to attack. This also damages the user quite a lot.' where id = 452;
update moves set description = 'The user lunges at the target at a speed that makes it almost invisible. This move always goes first.' where id = 453;
update moves set description = 'The user calls out its underlings to pummel the target. Critical hits land more easily.' where id = 454;
update moves set description = 'The user calls out its underlings to shield its body, raising its Defense and Sp. Def stats.' where id = 455;
update moves set description = 'The user calls out its underlings to heal it. The user regains up to half of its max HP.' where id = 456;
update moves set description = 'The user attacks the target with a hazardous, full-power headbutt. This also damages the user terribly.' where id = 457;
update moves set description = 'The user slams the target with a long tail, vines, or a tentacle. The target is hit twice in a row.' where id = 458;
update moves set description = 'The user blasts the target with power that distorts even time. The user can''t move on the next turn.' where id = 459;
update moves set description = 'The user tears the target along with the space around it. Critical hits land more easily.' where id = 460;
update moves set description = 'The user faints. In return, the Pokemon taking its place will have its status and HP fully restored.' where id = 461;
update moves set description = 'The target is crushed with great force. The more HP the target has left, the greater this move''s power.' where id = 462;
update moves set description = 'The target becomes trapped within a maelstrom of fire that rages for four to five turns.' where id = 463;
update moves set description = 'Opposing Pokemon are dragged into a world of total darkness that makes them sleep.' where id = 464;
update moves set description = 'The user emits a shock wave from its body to attack its target. This may also harshly lower the target''s Sp. Def.' where id = 465;
update moves set description = 'The user blasts the target with a gust of repulsive wind. This may also raise all the user''s stats at once.' where id = 466;
update moves set description = 'The user disappears, then strikes the target on the next turn. This move hits even if the target protects itself.' where id = 467;
update moves set description = 'The user sharpens its claws to boost its Attack stat and accuracy.' where id = 468;
update moves set description = 'The user and its allies are protected from wide-ranging attacks for one turn.' where id = 469;
update moves set description = 'The user employs its psychic power to average its Defense and Sp. Def stats with those of the target.' where id = 470;
update moves set description = 'The user employs its psychic power to average its Attack and Sp. Atk stats with those of the target.' where id = 471;
update moves set description = 'The user creates a bizarre area in which Pokemon''s Defense and Sp. Def stats are swapped for five turns.' where id = 472;
update moves set description = 'The user materializes an odd psychic wave to attack the target. This attack does physical damage.' where id = 473;
update moves set description = 'The user drenches the target in a special poisonous liquid. This move''s power is doubled if the target is poisoned.' where id = 474;
update moves set description = 'The user sheds part of its body to make itself lighter and sharply raise its Speed stat.' where id = 475;
update moves set description = 'The user scatters a cloud of irritating powder to draw attention to itself. Opponents aim only at the user.' where id = 476;
update moves set description = 'The user makes the target float with its psychic power. The target is easier to hit for three turns.' where id = 477;
update moves set description = 'The user creates a bizarre area in which Pokemon''s held items lose their effects for five turns.' where id = 478;
update moves set description = 'The user throws a stone or similar projectile to attack an opponent. A flying Pokemon will fall to the ground when it''s hit.' where id = 479;
update moves set description = 'The user strikes the target with a fierce blow. This attack always results in a critical hit.' where id = 480;
update moves set description = 'The user attacks the target with a bursting flame. The bursting flame damages Pokemon next to the target as well.' where id = 481;
update moves set description = 'The user strikes everything around it by swamping the area with a giant sludge wave. This may also poison those hit.' where id = 482;
update moves set description = 'The user lightly performs a beautiful, mystic dance. This boosts the user''s Sp. Atk, Sp. Def, and Speed stats.' where id = 483;
update moves set description = 'The user slams into the target with its heavy body. The more the user outweighs the target, the greater the move''s power.	' where id = 484;
update moves set description = 'Using an odd shock wave, the user inflicts damage on any Pokemon of the same type in the area around it.' where id = 485;
update moves set description = 'The user hurls an electric orb at the target. The faster the user is than the target, the greater the move''s power.' where id = 486;
update moves set description = 'The user shoots a torrent of water at the target and changes the target''s type to Water.' where id = 487;
update moves set description = 'Cloaking itself in flame, the user attacks. Then, building up more power, the user raises its Speed stat.' where id = 488;
update moves set description = 'The user coils up and concentrates. This raises its Attack and Defense stats as well as its accuracy.' where id = 489;
update moves set description = 'The user makes a swift attack on the target''s legs, which lowers the target''s Speed stat.' where id = 490;
update moves set description = 'The user spits fluid that works to melt the target. This harshly lowers the target''s Sp. Def stat.' where id = 491;
update moves set description = 'The user turns the target''s power against it. The higher the target''s Attack stat, the greater the move''s power.' where id = 492;
update moves set description = 'The user''s mysterious psychic wave changes the target''s Ability to Simple.' where id = 493;
update moves set description = 'The user dances with an odd rhythm that compels the target to mimic it, making the target''s Ability the same as the user''s.' where id = 494;
update moves set description = 'The user helps the target and makes it use its move right after the user.' where id = 495;
update moves set description = 'The user attacks the target with a song. Others can join in the Round and make the attack do greater damage.' where id = 496;
update moves set description = 'The user attacks the target with an echoing voice. If this move is used every turn, it does greater damage.' where id = 497;
update moves set description = 'Looking for an opening, the user strikes consistently. The target''s stat changes don''t affect this attack''s damage.' where id = 498;
update moves set description = 'The user attacks by throwing a clump of special mud. All stat changes are returned to normal.' where id = 499;
update moves set description = 'The user attacks the target with stored power. The more the user''s stats are raised, the greater the move''s power.' where id = 500;
update moves set description = 'The user protects itself and its allies from priority moves.' where id = 501;
update moves set description = 'The user teleports using a strange power and switches places with one of its allies.' where id = 502;
update moves set description = 'The user shoots boiling hot water at its target. This may also leave the target with a burn.' where id = 503;
update moves set description = 'The user breaks its shell, which lowers Defense and Sp. Def stats but sharply raises its Attack, Sp. Atk, and Speed stats.' where id = 504;
update moves set description = 'The user emits a healing pulse which restores the target''s HP by up to half of its max HP.' where id = 505;
update moves set description = 'This relentless attack does massive damage to a target affected by status conditions.' where id = 506;
update moves set description = 'The user takes the target into the sky, then drops it during the next turn. The target cannot attack while in the sky.	' where id = 507;
update moves set description = 'The user rotates its gears, raising its Attack and sharply raising its Speed.' where id = 508;
update moves set description = 'The target is thrown, and a different Pokemon is dragged out. In the wild, this ends a battle against a single Pokemon.' where id = 509;
update moves set description = 'The user attacks opposing Pokemon with fire. If a Pokemon is holding a certain item, such as a Berry, the item becomes burned up and unusable.' where id = 510;
update moves set description = 'The user suppresses the target and makes its move go last.' where id = 511;
update moves set description = 'The user nimbly strikes the target. If the user is not holding an item, this attack inflicts massive damage.' where id = 512;
update moves set description = 'The user reflects the target''s type, making it the same type as the target.' where id = 513;
update moves set description = 'The user gets revenge for a fainted ally. If an ally fainted in the previous turn, this move becomes more powerful.' where id = 514;
update moves set description = 'The user risks everything to attack its target. The user faints but does damage equal to its HP.' where id = 515;
update moves set description = 'The user passes its held item to the target when the target isn''t holding an item.' where id = 516;
update moves set description = 'The user attacks by engulfing the target in an intense fire. This leaves the target with a burn.' where id = 517;
update moves set description = 'A column of water strikes the target. When combined with its fire equivalent, the damage increases and a rainbow appears.' where id = 518;
update moves set description = 'A column of fire hits the target. When used with its grass equivalent, its damage increases and a vast sea of fire appears.' where id = 519;
update moves set description = 'A column of grass hits the target. When used with its water equivalent, its damage increases and a vast swamp appears.' where id = 520;
update moves set description = 'After making its attack, the user rushes back to switch places with a party Pokemon in waiting.' where id = 521;
update moves set description = 'While resisting, the user attacks the opposing Pokemon. This lowers the Sp. Atk stat of those hit.' where id = 522;
update moves set description = 'The user strikes everything around it by stomping down on the ground. This lowers the Speed stat of those hit.	' where id = 523;
update moves set description = 'The user blows its cold breath on the target. This attack always results in a critical hit.' where id = 524;
update moves set description = 'The target is knocked away, and a different Pokemon is dragged out. In the wild, this ends a battle against a single Pokemon.' where id = 525;
update moves set description = 'The user is roused, and its Attack and Sp. Atk stats increase.' where id = 526;
update moves set description = 'The user attacks and captures opposing Pokemon using an electric net. This lowers their Speed stat.' where id = 527;
update moves set description = 'The user shrouds itself in electricity and smashes into its target. This also damages the user a little.' where id = 528;
update moves set description = 'The user crashes into its target while rotating its body like a drill. Critical hits land more easily.' where id = 529;
update moves set description = 'The user attacks its target by hitting it with brutal strikes. The target is hit twice in a row.' where id = 530;
update moves set description = 'The user unleashes a vicious blow after its cute act makes the target less wary. This may also make the target flinch.' where id = 531;
update moves set description = 'The user drains the target''s energy with its horns. The user''s HP is restored by half the damage taken by the target.' where id = 532;
update moves set description = 'The user attacks by slicing with a long horn. The target''s stat changes don''t affect this attack''s damage.' where id = 533;
update moves set description = 'The user cuts its target with sharp shells. This may also lower the target''s Defense stat.' where id = 534;
update moves set description = 'The user slams its target with its flame- covered body. The more the user outweighs the target, the greater the move''s power.' where id = 535;
update moves set description = 'The user attacks its target by encircling it in sharp leaves. This attack may also lower the target''s accuracy.' where id = 536;
update moves set description = 'The user crushes its targets by rolling over them with its rolled-up body. This may also make the target flinch.' where id = 537;
update moves set description = 'The user protects itself by wrapping its body in soft cotton, which drastically raises the user''s Defense stat.' where id = 538;
update moves set description = 'The user lets loose a pitch-black shock wave at its target. This may also lower the target''s accuracy.' where id = 539;
update moves set description = 'The user materializes an odd psychic wave to attack the target. This attack does physical damage.' where id = 540;
update moves set description = 'The user attacks by striking the target with its hard tail. It hits the target two to five times in a row.' where id = 541;
update moves set description = 'The user attacks by wrapping its opponent in a fierce wind that flies up into the sky. This may also confuse the target.' where id = 542;
update moves set description = 'The user charges its head into its target, using its powerful guard hair. This also damages the user a little.' where id = 543;
update moves set description = 'The user attacks by throwing steel gears at its target twice.' where id = 544;
update moves set description = 'The user torches everything around it with an inferno of scarlet flames. This may also leave those hit with a burn.' where id = 545;
update moves set description = 'The user fires a beam of light at its target. The move''s type changes depending on the Drive the user holds.' where id = 546;
update moves set description = 'The user sings an ancient song and attacks by appealing to the hearts of the listening opposing Pokemon. This may also induce sleep.' where id = 547;
update moves set description = 'The user cuts with its long horn. The odd power contained in the horn does physical damage to the target.' where id = 548;
update moves set description = 'The user attacks by blowing freezing cold air at opposing Pokemon. This lowers their Speed stat.' where id = 549;
update moves set description = 'The user surrounds itself with a great amount of electricity and charges its target. This may also leave the target with paralysis.' where id = 550;
update moves set description = 'The user attacks by engulfing the target in an intense, yet beautiful, blue flame. This may also leave the target with a burn.' where id = 551;
update moves set description = 'Cloaked in flames, the user dances and flaps its wings. This may also raise the user''s Sp. Atk stat.' where id = 552;
update moves set description = 'On the second turn, the user hits the target with electrically charged ice. This may also leave the target with paralysis.' where id = 553;
update moves set description = 'On the second turn, an ultracold, freezing wind surrounds the target. This may leave the target with a burn.' where id = 554;
update moves set description = 'The user yells as if it''s ranting about something, which lowers the Sp. Atk stat of opposing Pokemon.' where id = 555;
update moves set description = 'The user attacks by harshly dropping large icicles onto the target. This may also make the target flinch.' where id = 556;
update moves set description = 'With a hot flame on its forehead, the user hurls itself at its target. This lowers the user''s Defense, Sp. Def, and Speed stats.' where id = 557;
update moves set description = 'The user brings down a giant flame. This move is more powerful when influenced by an enormous thunderbolt.' where id = 558;
update moves set description = 'The user throws down a giant thunderbolt. This move is more powerful when influenced by an enormous flame.' where id = 559;
update moves set description = 'The user dives down onto the target from the sky. This move is Fighting and Flying type simultaneously.' where id = 560;
update moves set description = 'Using a pulled-up mat as a shield, the user protects itself and its allies from damaging moves. This does not stop status moves.' where id = 561;
update moves set description = 'The user lets out a damaging belch at the target. The user must eat a held Berry to use this move.' where id = 562;
update moves set description = 'Tilling the soil, the user makes it easier for plants to grow. This raises the Attack and Sp. Atk stats of Grass-type Pokemon.' where id = 563;
update moves set description = 'The user weaves a sticky net around the opposing team, which lowers their Speed stat upon switching into battle.' where id = 564;
update moves set description = 'When the user knocks out a target with this move, the user''s Attack stat rises sharply.' where id = 565;
update moves set description = 'The user vanishes somewhere, then strikes the target on the next turn. This move hits even if the target protects itself.' where id = 566;
update moves set description = 'The user takes the target trick-or-treating. This adds Ghost type to the target''s type.' where id = 567;
update moves set description = 'Letting out a noble roar, the user intimidates the target and lowers its Attack and Sp. Atk stats.' where id = 568;
update moves set description = 'The user disperses electrically charged particles, which changes Normal-type moves to Electric-type moves.' where id = 569;
update moves set description = 'The user attacks everything around it. The user''s HP is restored by half the damage taken by those hit.' where id = 570;
update moves set description = 'The user puts a forest curse on the target. Afflicted targets are now Grass type as well.' where id = 571;
update moves set description = 'The user stirs up a violent petal blizzard and attacks everything around it.' where id = 572;
update moves set description = 'The user rapidly cools the target. This may also leave the target frozen. This move is super effective on Water types.' where id = 573;
update moves set description = 'Letting out a charming cry, the user does emotional damage to opposing Pokemon. This attack never misses.' where id = 574;
update moves set description = 'With a parting threat, the user lowers the target''s Attack and Sp. Atk stats. Then it switches with a party Pokemon.' where id = 575;
update moves set description = 'All stat changes affecting the target turn topsy-turvy and become the opposite of what they were.' where id = 576;
update moves set description = 'The user steals the target''s energy with a kiss. The user''s HP is restored by over half of the damage taken by the target.' where id = 577;
update moves set description = 'The user protects itself and its allies from status moves with a mysterious power. This does not stop moves that do damage.' where id = 578;
update moves set description = 'The user raises the Defense stat of all Grass-type Pokemon in battle with a mysterious power.' where id = 579;
update moves set description = 'The user turns the ground under everyone''s feet to grass for five turns. This restores the HP of Pokemon on the ground a little every turn.' where id = 580;
update moves set description = 'The user covers the ground under everyone''s feet with mist for five turns. This protects Pokemon on the ground from status conditions.' where id = 581;
update moves set description = 'If the target is electrified before it uses a move during that turn, the target''s move becomes Electric type.' where id = 582;
update moves set description = 'The user plays rough with the target and attacks it. This may also lower the target''s Attack stat.' where id = 583;
update moves set description = 'The user stirs up a fairy wind and strikes the target with it.' where id = 584;
update moves set description = 'Borrowing the power of the moon, the user attacks the target. This may also lower the target''s Sp. Atk stat.' where id = 585;
update moves set description = 'The user attacks everything around it with the destructive power of a terrible, explosive sound.' where id = 586;
update moves set description = 'By locking down the battlefield, the user keeps all Pokemon from fleeing during the next turn.' where id = 587;
update moves set description = 'The user takes a defensive stance while it protects itself from damage. It also harshly lowers the Attack stat of any attacker who makes direct contact.' where id = 588;
update moves set description = 'The user and the target become friends, and the target loses its will to fight. This lowers the target''s Attack stat.' where id = 589;
update moves set description = 'The user tells the target a secret, and the target loses its ability to concentrate. This lowers the target''s Sp. Atk stat.' where id = 590;
update moves set description = 'The user whips up a storm of diamonds to damage opposing Pokemon. This may also raise the user''s Defense stat.' where id = 591;
update moves set description = 'The user immerses the target in superheated steam. This may also leave the target with a burn.' where id = 592;
update moves set description = 'Using a hyperspace hole, the user appears right next to the target and strikes. This also hits a target using Protect or Detect.' where id = 593;
update moves set description = 'The user hits the target with throwing stars two to five times in a row. This move always goes first.' where id = 594;
update moves set description = 'The user attacks by breathing a special, hot fire. This also lowers the target''s Sp. Atk stat.' where id = 595;
update moves set description = 'In addition to protecting the user from attacks, this move also damages any attacker who makes direct contact.' where id = 596;
update moves set description = 'The user raises the Sp. Def stat of an ally Pokemon by using a mysterious aroma.' where id = 597;
update moves set description = 'The user''s body generates an eerie impulse. Exposing the target to it harshly lowers the target''s Sp. Atk stat.' where id = 598;
update moves set description = 'Opposing Pokemon are drenched in an odd poisonous liquid. This lowers the Attack, Sp. Atk, and Speed stats of a poisoned target.' where id = 599;
update moves set description = 'The user covers the target in a powder that explodes and damages the target if it uses a Fire-type move.' where id = 600;
update moves set description = 'The user absorbs energy and sharply raises its Sp. Atk, Sp. Def, and Speed stats on the next turn.' where id = 601;
update moves set description = 'The user manipulates magnetic fields, which raises the Defense and Sp. Def stats of ally Pokemon with the Plus or Minus Ability.' where id = 602;
update moves set description = 'Using Happy Hour doubles the amount of prize money received after battle.' where id = 603;
update moves set description = 'The user electrifies the ground under everyone''s feet for five turns. Pokemon on the ground no longer fall asleep.' where id = 604;
update moves set description = 'The user damages opposing Pokemon by emitting a powerful flash.' where id = 605;
update moves set description = 'The Pokemon congratulates you on your special day!' where id = 606;
update moves set description = 'The user and an ally hold hands. This makes them very happy.' where id = 607;
update moves set description = 'The user stares at the target with its baby-doll eyes, which lowers its Attack stat. This move always goes first.' where id = 608;
update moves set description = 'The user attacks by nuzzling its electrified cheeks against the target. This also leaves the target with paralysis.' where id = 609;
update moves set description = 'The user holds back when it attacks and the target is left with at least 1 HP.' where id = 610;
update moves set description = 'The target is infested and attacked for four to five turns. The target can''t flee during this time.' where id = 611;
update moves set description = 'Striking opponents over and over makes the user''s fists harder. Hitting a target raises the Attack stat.' where id = 612;
update moves set description = 'The user absorbs its target''s HP. The user''s HP is restored by over half of the damage taken by the target.' where id = 613;
update moves set description = 'This move also hits opposing Pokemon that are in the air. Those Pokemon are knocked down to the ground.' where id = 614;
update moves set description = 'The user attacks with a wave that crawls along the ground. Those hit can''t flee from battle.' where id = 615;
update moves set description = 'The user gathers the energy of the land and focuses that power on opposing Pokemon to damage them.' where id = 616;
update moves set description = 'Drawing power from the Eternal Flower, the user fires a powerful beam of light. This also damages the user quite a lot.' where id = 617;
update moves set description = 'The user attacks opposing Pokemon with countless beams of light that glow a deep and brilliant blue.' where id = 618;
update moves set description = 'The user attacks opposing Pokemon by manifesting the power of the land in fearsome blades of stone.' where id = 619;
update moves set description = 'After soaring upward, the user attacks its target by dropping out of the sky at high speeds, although it lowers its own Defense and Sp. Def in the process.' where id = 620;
update moves set description = 'Using its many arms, the user unleashes a barrage of attacks that ignore the effects of moves like Protect and Detect. This attack lowers the user''s Defense.' where id = 621;

end transaction;