begin transaction;

update abilities set description = 'The stench may cause the target to flinch.' where id =  1;
update abilities set description = 'The Pokemon makes it rain if it appears in battle.' where id =  2;
update abilities set description = 'The Pokemon''s Speed stat is gradually boosted.' where id =  3;
update abilities set description = 'The Pokemon is protected against critical hits.' where id =  4;
update abilities set description = 'The Pokemon is protected against 1-hit KO attacks.' where id =  5;
update abilities set description = 'Prevents combatants from self destructing.' where id =  6;
update abilities set description = 'The Pokemon is protected from paralysis.' where id =  7;
update abilities set description = 'Boosts the Pokemon''s evasion in a sandstorm.' where id =  8;
update abilities set description = 'Contact with the Pokemon may cause paralysis.' where id =  9;
update abilities set description = 'Restores HP if hit by an Electric-type move.' where id =  10;
update abilities set description = 'Restores HP if hit by a Water-type move.' where id =  11;
update abilities set description = 'Prevents the Pokemon from becoming infatuated or falling for taunts.' where id =  12;
update abilities set description = 'Eliminates the effects of weather.' where id =  13;
update abilities set description = 'The Pokemon''s accuracy is boosted.' where id =  14;
update abilities set description = 'Prevents the Pokemon from falling asleep.' where id =  15;
update abilities set description = 'Changes the Pokemon''s type to the foe''s move.' where id =  16;
update abilities set description = 'Prevents the Pokemon from getting poisoned.' where id =  17;
update abilities set description = 'Powers up Fire-type moves if hit by a fire move.' where id =  18;
update abilities set description = 'Blocks the added effects of attacks taken.' where id =  19;
update abilities set description = 'Prevents the Pokemon from becoming confused.' where id =  20;
update abilities set description = 'Negates moves that force switching out.' where id =  21;
update abilities set description = 'Lowers the foe''s Attack stat.' where id =  22;
update abilities set description = 'Prevents the foe from escaping.' where id =  23;
update abilities set description = 'Inflicts damage to the foe on contact.' where id =  24;
update abilities set description = 'Only supereffective moves will hit.' where id =  25;
update abilities set description = 'Gives full immunity to all Ground-type moves.' where id =  26;
update abilities set description = 'Contact may paralyze, poison, or cause sleep.' where id =  27;
update abilities set description = 'Passes on a burn, poison, or paralysis to the foe.' where id =  28;
update abilities set description = 'Prevents the Pokemon''s stats from being lowered.' where id =  29;
update abilities set description = 'All status problems are healed upon switching out.' where id =  30;
update abilities set description = 'The Pokemon draws in all Electric-type moves to raise Sp.Atk.' where id =  31;
update abilities set description = 'Boosts the likelihood of added effects appearing.' where id =  32;
update abilities set description = 'Boosts the Pokemon''s Speed in rain.' where id =  33;
update abilities set description = 'Boosts the Pokemon''s Speed in sunshine.' where id =  34;
update abilities set description = 'Raises the likelihood of meeting wild Pokemon.' where id =  35;
update abilities set description = 'The Pokemon copies a foe''s Ability.' where id =  36;
update abilities set description = 'Raises the Pokemon''s Attack stat.' where id =  37;
update abilities set description = 'Contact with the Pokemon may poison the foe.' where id =  38;
update abilities set description = 'The Pokemon is protected from flinching.' where id =  39;
update abilities set description = 'Prevents the Pokemon from becoming frozen.' where id =  40;
update abilities set description = 'Prevents the Pokemon from getting a burn.' where id =  41;
update abilities set description = 'Prevents Steel-type Pokemon from escaping.' where id =  42;
update abilities set description = 'Gives full immunity to all sound-based moves.' where id =  43;
update abilities set description = 'The Pokemon gradually recovers HP in rain.' where id =  44;
update abilities set description = 'The Pokemon summons a sandstorm in battle.' where id =  45;
update abilities set description = 'The Pokemon raises the foe''s PP usage.' where id =  46;
update abilities set description = 'Raises resistance to Fire- and Ice-type moves.' where id =  47;
update abilities set description = 'The Pokemon awakens quickly from sleep.' where id =  48;
update abilities set description = 'Contact with the Pokemon may burn the foe.' where id =  49;
update abilities set description = 'Enables sure getaway from wild Pokemon.' where id =  50;
update abilities set description = 'Prevents the Pokemon from losing accuracy.' where id =  51;
update abilities set description = 'Prevents the Attack stat from being lowered.' where id =  52;
update abilities set description = 'The Pokemon may pick up items.' where id =  53;
update abilities set description = 'The Pokemon can''t attack on consecutive turns.' where id =  54;
update abilities set description = 'Boosts the Attack stat, but lowers accuracy.' where id =  55;
update abilities set description = 'Contact with the Pokemon may cause infatuation.' where id =  56;
update abilities set description = 'Boosts Sp. Atk if another Pokemon has Minus.' where id =  57;
update abilities set description = 'Boosts Sp. Atk if another Pokemon has Plus.' where id =  58;
update abilities set description = 'Transforms with the weather.' where id =  59;
update abilities set description = 'Protects the Pokemon from item theft.' where id =  60;
update abilities set description = 'The Pokemon may heal its own status problems.' where id =  61;
update abilities set description = 'Boosts Attack if there is a status problem.' where id =  62;
update abilities set description = 'Boosts Defense if there is a status problem.' where id =  63;
update abilities set description = 'Inflicts damage on foes using any draining move.' where id =  64;
update abilities set description = 'Powers up Grass-type moves in a pinch.' where id =  65;
update abilities set description = 'Powers up Fire-type moves in a pinch.' where id =  66;
update abilities set description = 'Powers up Water-type moves in a pinch.' where id =  67;
update abilities set description = 'Powers up Bug-type moves in a pinch.' where id =  68;
update abilities set description = 'Protects the Pokemon from recoil damage.' where id =  69;
update abilities set description = 'The Pokemon makes it sunny if it is in battle.' where id =  70;
update abilities set description = 'Prevents the foe from fleeing.' where id =  71;
update abilities set description = 'Prevents the Pokemon from falling asleep.' where id =  72;
update abilities set description = 'Prevents the Pokemon''s stats from being lowered.' where id =  73;
update abilities set description = 'Boosts the power of physical attacks.' where id =  74;
update abilities set description = 'The Pokemon is protected against critical hits.' where id =  75;
update abilities set description = 'Eliminates the effects of weather.' where id =  76;
update abilities set description = 'Raises evasion if the Pokemon is confused.' where id =  77;
update abilities set description = 'Raises Speed if hit by an Electric-type move.' where id =  78;
update abilities set description = 'Raises Attack if the foe is of the same gender.' where id =  79;
update abilities set description = 'Raises Speed each time the Pokemon flinches.' where id =  80;
update abilities set description = 'Raises evasion in a hailstorm.' where id =  81;
update abilities set description = 'Encourages the early use of a held Berry.' where id =  82;
update abilities set description = 'Raises Attack upon taking a critical hit.' where id =  83;
update abilities set description = 'Raises Speed if a held item is used.' where id =  84;
update abilities set description = 'Weakens the power of Fire-type moves.' where id =  85;
update abilities set description = 'The Pokemon is prone to wild stat changes.' where id =  86;
update abilities set description = 'Reduces HP if it is hot. Water restores HP.' where id =  87;
update abilities set description = 'Adjusts power according to the foe''s lowest defensive stat.' where id =  88;
update abilities set description = 'Boosts the power of punching moves.' where id =  89;
update abilities set description = 'Restores HP if the Pokemon is poisoned.' where id =  90;
update abilities set description = 'Powers up moves of the same type.' where id =  91;
update abilities set description = 'Increases the frequency of multi-strike moves.' where id =  92;
update abilities set description = 'Heals status problems if it is raining.' where id =  93;
update abilities set description = 'Boosts Sp. Atk, but lowers HP in sunshine.' where id =  94;
update abilities set description = 'Boosts Speed if there is a status problem.' where id =  95;
update abilities set description = 'All the Pokemon''s moves become Normal type.' where id =  96;
update abilities set description = 'Powers up moves if they become critical hits.' where id =  97;
update abilities set description = 'The Pokemon only takes damage from attacks.' where id =  98;
update abilities set description = 'Ensures the Pokemon and its foe''s attacks land.' where id =  99;
update abilities set description = 'The Pokemon moves after even slower foes.' where id =  100;
update abilities set description = 'Powers up the Pokemon''s weaker moves.' where id =  101;
update abilities set description = 'Prevents status problems in sunny weather.' where id =  102;
update abilities set description = 'The Pokemon can''t use any held items.' where id =  103;
update abilities set description = 'Moves can be used regardless of Abilities.' where id =  104;
update abilities set description = 'Heightens the critical-hit ratios of moves.' where id =  105;
update abilities set description = 'Damages the foe landing the finishing hit.' where id =  106;
update abilities set description = 'Senses the foe''s dangerous moves.' where id =  107;
update abilities set description = 'Determines what moves the foe has.' where id =  108;
update abilities set description = 'Ignores any change in stats by the foe.' where id =  109;
update abilities set description = 'Powers up "not very effective" moves.' where id =  110;
update abilities set description = 'Powers down supereffective moves.' where id =  111;
update abilities set description = 'Temporarily halves Attack and Speed.' where id =  112;
update abilities set description = 'Enables moves to hit Ghost-type foes.' where id =  113;
update abilities set description = 'The Pokemon draws in all Water-type moves.' where id =  114;
update abilities set description = 'The Pokemon regains HP in a hailstorm.' where id =  115;
update abilities set description = 'Powers down supereffective moves.' where id =  116;
update abilities set description = 'The Pokemon summons a hailstorm in battle.' where id =  117;
update abilities set description = 'The Pokemon may gather Honey from somewhere.' where id =  118;
update abilities set description = 'The Pokemon can check the foe''s held item.' where id =  119;
update abilities set description = 'Powers up moves that have recoil damage.' where id =  120;
update abilities set description = 'Changes type to match the held Plate.' where id =  121;
update abilities set description = 'Powers up party Pokemon when it is sunny.' where id =  122;
update abilities set description = 'Reduces a sleeping foe''s HP.' where id =  123;
update abilities set description = 'Steals attacking Pokemon''s held item on contact.' where id =  124;
update abilities set description = 'Strengthens moves with extra effects to 1.3× their power, but prevents their extra effects.' where id =  125;
update abilities set description = 'Inverts stat modifiers.' where id =  126;
update abilities set description = 'Prevents opposing Pokemon from eating held Berries.' where id =  127;
update abilities set description = 'Raises Attack two stages upon having any stat lowered.' where id =  128;
update abilities set description = 'Halves Attack and Special Attack below 50% HP.' where id =  129;
update abilities set description = 'Has a 30% chance of Disabling any move that hits the Pokemon.' where id =  130;
update abilities set description = 'Has a 30% chance of curing each adjacent ally of any major status ailment after each turn.' where id =  131;
update abilities set description = 'Decreases damage inflicted against ally Pokemon.' where id =  132;
update abilities set description = 'Raises Speed and lowers Defense by one stage each upon being hit by any move.' where id =  133;
update abilities set description = 'Doubles the Pokemon''s weight.' where id =  134;
update abilities set description = 'Pokemon''s Halves the Pokemon''s weight.' where id =  135;
update abilities set description = 'Halves damage taken from full HP.' where id =  136;
update abilities set description = 'Increases Attack to 1.5x when poisoned.' where id =  137;
update abilities set description = 'Increases Special Attack to 1.5x when burned.' where id =  138;
update abilities set description = 'Sometimes restores a consumed Berry.' where id =  139;
update abilities set description = 'Protects against damaging moves from friendly Pokemon.' where id =  140;
update abilities set description = 'Raises a random stat two stages and lowers another one stage after each turn.' where id =  141;
update abilities set description = 'Protects against damage from weather.' where id =  142;
update abilities set description = 'Has a 30% chance of poisoning Pokemon upon contact when attacking.' where id =  143;
update abilities set description = 'Heals for 1/3 max HP upon leaving battle.' where id =  144;
update abilities set description = 'Protects the Pokemon from Defense-lowering attacks.' where id =  145;
update abilities set description = 'Doubles Speed during a sandstorm.' where id =  146;
update abilities set description = 'Has a 50% chance of protecting against non-damaging moves that inflict major status ailments.' where id =  147;
update abilities set description = 'Strengthens moves when moving last.' where id =  148;
update abilities set description = 'Takes the appearance of the last conscious party Pokemon upon being sent out until hit by a damaging move.' where id =  149;
update abilities set description = 'Transforms upon entering battle.' where id =  150;
update abilities set description = 'Ignores Light Screen, Reflect, and Safeguard.' where id =  151;
update abilities set description = 'Contact with this Pokemon spreads this Ability.' where id =  152;
update abilities set description = 'Raises Attack one stage upon KOing a Pokemon.' where id =  153;
update abilities set description = 'Raises Attack when hit by Dark-type moves.' where id =  154;
update abilities set description = 'Raises Speed one stage upon being hit by a Dark, Ghost, or Bug move.' where id =  155;
update abilities set description = 'Reflects most non-damaging moves back at their user.' where id =  156;
update abilities set description = 'Absorbs Grass moves, raising Attack one stage.' where id =  157;
update abilities set description = 'Raises non-damaging moves'' priority by one stage.	' where id =  158;
update abilities set description = 'Strengthens Rock, Ground, and Steel moves to 1.3× their power during a sandstorm.' where id =  159;
update abilities set description = 'Damages attacking Pokemon for 1/8 their max HP on contact.' where id =  160;
update abilities set description = 'Changes the Pokemon''s shape when HP is halved.' where id =  161;
update abilities set description = 'Raises moves'' accuracy to 1.1x for friendly Pokemon.' where id =  162;
update abilities set description = 'Moves can be used regardless of Abilities.' where id =  163;
update abilities set description = 'Moves can be used regardless of Abilities.' where id =  164;
update abilities set description = 'Protects allies from attacks that limit their move choices.' where id =  165;
update abilities set description = 'Prevents lowering of ally Grass-type Pokemon''s stats.' where id =  166;
update abilities set description = 'Restores HP as well when the Pokemon eats a Berry.' where id =  167;
update abilities set description = 'Changes the Pokemon''s type to the same type of the move it is using.' where id =  168;
update abilities set description = 'Halves damage from physical moves.' where id =  169;
update abilities set description = 'The Pokemon steals the held item of a Pokemon it hits with a move.' where id =  170;
update abilities set description = 'Protects the Pokemon from some ball and bomb moves.' where id =  171;
update abilities set description = 'Boosts the Sp.Atk stat when a stat is lowered.' where id =  172;
update abilities set description = 'The Pokemon''s strong jaw gives it tremendous biting power.' where id =  173;
update abilities set description = 'Normal-type moves become Ice-type moves.' where id =  174;
update abilities set description = 'Prevents itself and its allies from falling asleep.' where id =  175;
update abilities set description = 'The Pokemon changes form depending on how it battles.' where id =  176;
update abilities set description = 'Gives priority to Flying-type moves.' where id =  177;
update abilities set description = 'Powers up aura and pulse moves.' where id =  178;
update abilities set description = 'Boosts the Defense stat in Grassy Terrain.' where id =  179;
update abilities set description = 'The Pokemon can pass an item to an ally.' where id =  180;
update abilities set description = 'Powers up moves that make direct contact.' where id =  181;
update abilities set description = 'Normal-type moves become Fairy-type moves.' where id =  182;
update abilities set description = 'Contact with the Pokemon lowers the attacker''s Speed stat.' where id =  183;
update abilities set description = 'Normal-type moves become Flying-type moves.' where id =  184;
update abilities set description = 'Parent and child attack together.' where id =  185;
update abilities set description = 'Powers up each Pokemon''s Dark-type moves.' where id =  186;
update abilities set description = 'Powers up each Pokemon''s Fairy-type moves.' where id =  187;
update abilities set description = 'The effects of "Aura" Abilities are reversed.' where id =  188;
update abilities set description = 'Causes heavy rain.' where id =  189;
update abilities set description = 'Creates harsh sunlight.' where id =  190;
update abilities set description = 'Eliminates weather effects and eliminates weaknesses of Flying-type Pokemon.' where id =  191;

end transaction;
